In [1]:
import pandas as pd

# Load employer dataset

df_employer = pd.read_excel(r"C:\Users\User\Desktop\youth unemployement\Employers’_Perspectives_on_Yout2026-08-31_04_33_17.xlsx")
# Basic overview
print("Shape:", df_employer.shape)

print("\nColumn names:")
for i, col in enumerate(df_employer.columns):
    print(f"{i}: {col}")

print("\nData types:")
print(df_employer.dtypes)

print("\nMissing values:")
print(df_employer.isna().sum())

print("\nUnique values per feature:")
print(df_employer.nunique(dropna=False))

Shape: (36, 25)

Column names:
0: Submission Date
1: What is your industry or sector?
2: Approximately how many employees does your organization currently have ?
3: What is your role in the hiring process?
4: In the last 12 months, approximately how many people under 30 did your organization hire?
5: In the past 12 months, which of the following challenges, if any, have you experienced when hiring?
6: When recruiting for junior or entry-level positions, where do you usually find candidates?
7: What are the THREE most important factors you consider when deciding whether to interview or seriously consider a young candidate?
8: What are the THREE most common reasons a young applicant is not selected for the next stage or ultimately not hired?
9: How important are the following factors when deciding whether to interview or hire a young candidate? >> Technical skills
10: How important are the following factors when deciding whether to interview or hire a young candidate? >> Practical experience
11: How important are the following factors when deciding whether to interview or hire a young candidate? >> Communication
12: How important are the following factors when deciding whether to interview or hire a young candidate? >> Problem-solving
13: How important are the following factors when deciding whether to interview or hire a young candidate? >> Ability to learn
14: How important are the following factors when deciding whether to interview or hire a young candidate? >> Degree / academic background
15: How important are the following factors when deciding whether to interview or hire a young candidate? >> Previous internship
16: How important are the following factors when deciding whether to interview or hire a young candidate? >> English / language skills
17: In your industry, how would you describe the availability of entry-level jobs for young people?
18: For a typical entry-level position, what level of previous experience do you normally expect?
19: When a promising young candidate does not have all the skills or experience required for a position, what does your organization usually do?
20: How important are personal or professional connections in helping young candidates access employment opportunities in your industry?
21: If two young candidates had similar qualifications, skills, and experience, and one graduated from Lebanese University while the other graduated from a private university, which candidate would you be more likely to hire?
22: How often do you think entry-level positions in your industry require more experience or qualifications than are realistically necessary to perform the job?
23: What are the main reasons young employees leave your organization?
24: Which TWO or THREE changes would most improve young people’s ability to obtain and keep employment in Lebanon?

Data types:
Submission Date                                                                                                                                                                                                                  object
What is your industry or sector?                                                                                                                                                                                                 object
Approximately how many employees does your organization currently have ?                                                                                                                                                         object
What is your role in the hiring process?                                                                                                                                                                                         object
In the last 12 months, approximately how many people under 30 did your organization hire?                                                                                                                                        object
In the past 12 months, which of the following challenges, if any, have you experienced when hiring?                                                                                                                              object
When recruiting for junior or entry-level positions, where do you usually find candidates?                                                                                                                                       object
What are the THREE most important factors you consider when deciding whether to interview or seriously consider a young candidate?                                                                                               object
What are the THREE most common reasons a young applicant is not selected for the next stage or ultimately not hired?                                                                                                             object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Technical skills                                                                                                        object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Practical experience                                                                                                    object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Communication                                                                                                           object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Problem-solving                                                                                                         object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Ability to learn                                                                                                        object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Degree / academic background                                                                                            object
How important are the following factors when deciding whether to interview or hire a young candidate? >> Previous internship                                                                                                     object
How important are the following factors when deciding whether to interview or hire a young candidate? >> English / language skills                                                                                               object
In your industry, how would you describe the availability of entry-level jobs for young people?                                                                                                                                  object
For a typical entry-level position, what level of previous experience do you normally expect?                                                                                                                                    object
When a promising young candidate does not have all the skills or experience required for a position, what does your organization usually do?                                                                                     object
How important are personal or professional connections in helping young candidates access employment opportunities in your industry?                                                                                             object
If two young candidates had similar qualifications, skills, and experience, and one graduated from Lebanese University while the other graduated from a private university, which candidate would you be more likely to hire?    object
How often do you think entry-level positions in your industry require more experience or qualifications than are realistically necessary to perform the job?                                                                     object
What are the main reasons young employees leave your organization?                                                                                                                                                               object
Which TWO or THREE changes would most improve young people’s ability to obtain and keep employment in Lebanon?                                                                                                                   object
dtype: object

Missing values:
Submission Date                                                                                                                                                                                                                  0
What is your industry or sector?                                                                                                                                                                                                 0
Approximately how many employees does your organization currently have ?                                                                                                                                                         0
What is your role in the hiring process?                                                                                                                                                                                         0
In the last 12 months, approximately how many people under 30 did your organization hire?                                                                                                                                        3
In the past 12 months, which of the following challenges, if any, have you experienced when hiring?                                                                                                                              0
When recruiting for junior or entry-level positions, where do you usually find candidates?                                                                                                                                       0
What are the THREE most important factors you consider when deciding whether to interview or seriously consider a young candidate?                                                                                               0
What are the THREE most common reasons a young applicant is not selected for the next stage or ultimately not hired?                                                                                                             0
How important are the following factors when deciding whether to interview or hire a young candidate? >> Technical skills                                                                                                        1
How important are the following factors when deciding whether to interview or hire a young candidate? >> Practical experience                                                                                                    0
How important are the following factors when deciding whether to interview or hire a young candidate? >> Communication                                                                                                           0
How important are the following factors when deciding whether to interview or hire a young candidate? >> Problem-solving                                                                                                         0
How important are the following factors when deciding whether to interview or hire a young candidate? >> Ability to learn                                                                                                        1
How important are the following factors when deciding whether to interview or hire a young candidate? >> Degree / academic background                                                                                            0
How important are the following factors when deciding whether to interview or hire a young candidate? >> Previous internship                                                                                                     1
How important are the following factors when deciding whether to interview or hire a young candidate? >> English / language skills                                                                                               0
In your industry, how would you describe the availability of entry-level jobs for young people?                                                                                                                                  0
For a typical entry-level position, what level of previous experience do you normally expect?                                                                                                                                    0
When a promising young candidate does not have all the skills or experience required for a position, what does your organization usually do?                                                                                     0
How important are personal or professional connections in helping young candidates access employment opportunities in your industry?                                                                                             0
If two young candidates had similar qualifications, skills, and experience, and one graduated from Lebanese University while the other graduated from a private university, which candidate would you be more likely to hire?    0
How often do you think entry-level positions in your industry require more experience or qualifications than are realistically necessary to perform the job?                                                                     0
What are the main reasons young employees leave your organization?                                                                                                                                                               0
Which TWO or THREE changes would most improve young people’s ability to obtain and keep employment in Lebanon?                                                                                                                   0
dtype: int64

Unique values per feature:
Submission Date                                                                                                                                                                                                                   8
What is your industry or sector?                                                                                                                                                                                                 10
Approximately how many employees does your organization currently have ?                                                                                                                                                          5
What is your role in the hiring process?                                                                                                                                                                                          5
In the last 12 months, approximately how many people under 30 did your organization hire?                                                                                                                                         5
In the past 12 months, which of the following challenges, if any, have you experienced when hiring?                                                                                                                              26
When recruiting for junior or entry-level positions, where do you usually find candidates?                                                                                                                                       29
What are the THREE most important factors you consider when deciding whether to interview or seriously consider a young candidate?                                                                                               29
What are the THREE most common reasons a young applicant is not selected for the next stage or ultimately not hired?                                                                                                             33
How important are the following factors when deciding whether to interview or hire a young candidate? >> Technical skills                                                                                                         6
How important are the following factors when deciding whether to interview or hire a young candidate? >> Practical experience                                                                                                     5
How important are the following factors when deciding whether to interview or hire a young candidate? >> Communication                                                                                                            4
How important are the following factors when deciding whether to interview or hire a young candidate? >> Problem-solving                                                                                                          4
How important are the following factors when deciding whether to interview or hire a young candidate? >> Ability to learn                                                                                                         5
How important are the following factors when deciding whether to interview or hire a young candidate? >> Degree / academic background                                                                                             5
How important are the following factors when deciding whether to interview or hire a young candidate? >> Previous internship                                                                                                      6
How important are the following factors when deciding whether to interview or hire a young candidate? >> English / language skills                                                                                                4
In your industry, how would you describe the availability of entry-level jobs for young people?                                                                                                                                   7
For a typical entry-level position, what level of previous experience do you normally expect?                                                                                                                                     5
When a promising young candidate does not have all the skills or experience required for a position, what does your organization usually do?                                                                                      7
How important are personal or professional connections in helping young candidates access employment opportunities in your industry?                                                                                              6
If two young candidates had similar qualifications, skills, and experience, and one graduated from Lebanese University while the other graduated from a private university, which candidate would you be more likely to hire?     3
How often do you think entry-level positions in your industry require more experience or qualifications than are realistically necessary to perform the job?                                                                      7
What are the main reasons young employees leave your organization?                                                                                                                                                               28

In [2]:
new_names_employer = [
    "submission_date",
    "industry",
    "organization_size",
    "hiring_role",
    "youth_hired_12m",
    "hiring_challenges",
    "recruitment_sources",
    "top_interview_factors",
    "reasons_not_selected",
    "importance_technical_skills",
    "importance_practical_experience",
    "importance_communication",
    "importance_problem_solving",
    "importance_ability_to_learn",
    "importance_degree",
    "importance_previous_internship",
    "importance_language_skills",
    "entry_level_job_availability",
    "expected_previous_experience",
    "response_to_skill_gap",
    "importance_connections",
    "university_preference",
    "unnecessary_requirements",
    "youth_turnover_reasons",
    "employment_improvements"
]

df_employer.columns = new_names_employer

In [3]:
for i, col in enumerate(df_employer.columns):
    print(i, ":", col)

0 : submission_date
1 : industry
2 : organization_size
3 : hiring_role
4 : youth_hired_12m
5 : hiring_challenges
6 : recruitment_sources
7 : top_interview_factors
8 : reasons_not_selected
9 : importance_technical_skills
10 : importance_practical_experience
11 : importance_communication
12 : importance_problem_solving
13 : importance_ability_to_learn
14 : importance_degree
15 : importance_previous_internship
16 : importance_language_skills
17 : entry_level_job_availability
18 : expected_previous_experience
19 : response_to_skill_gap
20 : importance_connections
21 : university_preference
22 : unnecessary_requirements
23 : youth_turnover_reasons
24 : employment_improvements

In [4]:
# Remove submission date
df_employer = df_employer.drop(columns=["submission_date"])

# Create unique employer ID
df_employer.insert(
    0,
    "emp_id",
    [f"EMP{i:03d}" for i in range(1, len(df_employer) + 1)]
)

# Check
print(df_employer.shape)
print(df_employer.columns.tolist())

(36, 25)
['emp_id', 'industry', 'organization_size', 'hiring_role', 'youth_hired_12m', 'hiring_challenges', 'recruitment_sources', 'top_interview_factors', 'reasons_not_selected', 'importance_technical_skills', 'importance_practical_experience', 'importance_communication', 'importance_problem_solving', 'importance_ability_to_learn', 'importance_degree', 'importance_previous_internship', 'importance_language_skills', 'entry_level_job_availability', 'expected_previous_experience', 'response_to_skill_gap', 'importance_connections', 'university_preference', 'unnecessary_requirements', 'youth_turnover_reasons', 'employment_improvements']

In [5]:
#employer id display
print(df_employer["emp_id"].head())

0    EMP001
1    EMP002
2    EMP003
3    EMP004
4    EMP005
Name: emp_id, dtype: object

In [6]:
# Lowercase all text/categorical features
for col in df_employer.columns:
    if col != "emp_id":
        df_employer[col] = (
            df_employer[col]
            .astype("string")
            .str.lower()
            .str.strip()
        )

In [7]:
# Convert all features except emp_id to categorical
for col in df_employer.columns:
    if col != "emp_id":
        df_employer[col] = df_employer[col].astype("category")

# Check data types
print(df_employer.dtypes)

emp_id                               object
industry                           category
organization_size                  category
hiring_role                        category
youth_hired_12m                    category
hiring_challenges                  category
recruitment_sources                category
top_interview_factors              category
reasons_not_selected               category
importance_technical_skills        category
importance_practical_experience    category
importance_communication           category
importance_problem_solving         category
importance_ability_to_learn        category
importance_degree                  category
importance_previous_internship     category
importance_language_skills         category
entry_level_job_availability       category
expected_previous_experience       category
response_to_skill_gap              category
importance_connections             category
university_preference              category
unnecessary_requirements           category
youth_turnover_reasons             category
employment_improvements            category
dtype: object

In [8]:
# Show all categories for each categorical feature

for col in df_employer.select_dtypes(include="category").columns:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)
    
    for i, category in enumerate(df_employer[col].cat.categories, start=1):
        print(f"{i}. {category}")

================================================================================
industry
================================================================================
1. education
2. engineering / construction
3. finance / banking
4. healthcare
5. hospitality / tourism / f&b
6. manufacturing / industry
7. marketing / advertising
8. other
9. professional / business services
10. technology / it

================================================================================
organization_size
================================================================================
1. 11–50
2. 1–10
3. 251–500
4. 51–250
5. more than 500

================================================================================
hiring_role
================================================================================
1. department head
2. hiring manager / team lead
3. hr / recruitment
4. other
5. owner / founder

================================================================================
youth_hired_12m
================================================================================
1. 1–2
2. 3–5
3. 6–10
4. more than 10

================================================================================
hiring_challenges
================================================================================
1. candidates expected higher salaries than we could offer
2. candidates expected higher salaries than we could offer
suitable candidates accepted but later left
3. candidates lacked the experience we expected
4. suitable candidates accepted but later left
5. suitable candidates accepted but later left
we did not experience significant difficulty hiring
6. we did not experience significant difficulty hiring
7. we did not experience significant difficulty hiring
we did not have positions to fill
8. we did not have positions to fill
9. we received many applicants, but few met our requirements
10. we received many applicants, but few met our requirements
candidates lacked the experience we expected
11. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates expected higher salaries than we could offer
12. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
candidates expected higher salaries than we could offer
13. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
candidates were unavailable because of location, transportation, or working hours
14. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
suitable candidates declined our offers
candidates expected higher salaries than we could offer
15. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
suitable candidates declined our offers
candidates were unavailable because of location, transportation, or working hours
16. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
suitable candidates declined our offers
candidates were unavailable because of location, transportation, or working hours
candidates expected higher salaries than we could offer
suitable candidates accepted but later left
17. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
suitable candidates declined our offers
candidates were unavailable because of location, transportation, or working hours
candidates expected higher salaries than we could offer
we did not experience significant difficulty hiring
we did not have positions to fill
18. we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates lacked the skills we needed
we did not have positions to fill
19. we received many applicants, but few met our requirements
candidates lacked the experience we expected
suitable candidates declined our offers
candidates were unavailable because of location, transportation, or working hours
candidates expected higher salaries than we could offer
20. we received many applicants, but few met our requirements
candidates lacked the skills we needed
candidates were unavailable because of location, transportation, or working hours
21. we received many applicants, but few met our requirements
candidates lacked the skills we needed
suitable candidates declined our offers
candidates expected higher salaries than we could offer
22. we received many applicants, but few met our requirements
candidates lacked the skills we needed
we did not experience significant difficulty hiring
23. we received many applicants, but few met our requirements
suitable candidates declined our offers
candidates were unavailable because of location, transportation, or working hours
candidates expected higher salaries than we could offer
suitable candidates accepted but later left
24. we received many applicants, but few met our requirements
we did not have positions to fill
25. we received too few applicants
candidates lacked the skills we needed
26. we received too few applicants
we received many applicants, but few met our requirements
candidates lacked the experience we expected
candidates were unavailable because of location, transportation, or working hours

================================================================================
recruitment_sources
================================================================================
1. direct applications
2. employee referrals
direct applications
3. employee referrals
personal or professional networks
direct applications
4. employee referrals
personal or professional networks
recommendations from professors / teachers
5. linkedin
6. linkedin
employee referrals
7. linkedin
employee referrals
direct applications
8. linkedin
employee referrals
personal or professional networks
universities / career offices
9. linkedin
employee referrals
personal or professional networks
universities / career offices
internships / previous interns
direct applications
recommendations from professors / teachers
10. linkedin
employee referrals
personal or professional networks
universities / career offices
social media
11. linkedin
employee referrals
universities / career offices
12. linkedin
internships / previous interns
social media
13. linkedin
personal or professional networks
direct applications
14. linkedin
personal or professional networks
internships / previous interns
direct applications
15. linkedin
social media
recruitment agencies
16. personal or professional networks
universities / career offices
17. personal or professional networks
universities / career offices
direct applications
recommendations from professors / teachers
18. public job postings / job platforms
linkedin
19. public job postings / job platforms
linkedin
direct applications
20. public job postings / job platforms
linkedin
employee referrals
21. public job postings / job platforms
linkedin
employee referrals
personal or professional networks
22. public job postings / job platforms
linkedin
employee referrals
personal or professional networks
universities / career offices
internships / previous interns
recruitment agencies
direct applications
23. public job postings / job platforms
linkedin
employee referrals
personal or professional networks
universities / career offices
internships / previous interns
social media
recruitment agencies
direct applications
recommendations from professors / teachers
24. public job postings / job platforms
linkedin
employee referrals
personal or professional networks
universities / career offices
social media
direct applications
25. public job postings / job platforms
linkedin
social media
26. public job postings / job platforms
linkedin
universities / career offices
social media
27. public job postings / job platforms
social media
28. social media
29. universities / career offices
social media
direct applications

================================================================================
top_interview_factors
================================================================================
1. ability to learn / adaptability
education / degree
english / language skills
2. ability to learn / adaptability
motivation
education / degree
3. communication skills
ability to learn / adaptability
motivation
4. communication skills
motivation
education / degree
5. communication skills
motivation
professionalism
6. communication skills
problem-solving ability
ability to learn / adaptability
7. communication skills
problem-solving ability
university attended
8. internship experience
communication skills
motivation
9. internship experience
education / degree
salary expectations
10. practical projects / portfolio
communication skills
ability to learn / adaptability
11. previous work experience
communication skills
problem-solving ability
12. previous work experience
problem-solving ability
professionalism
13. previous work experience
referral / recommendation
professional network
14. technical / job-specific skills
ability to learn / adaptability
education / degree
15. technical / job-specific skills
ability to learn / adaptability
referral / recommendation
16. technical / job-specific skills
communication skills
ability to learn / adaptability
17. technical / job-specific skills
communication skills
availability / flexibility
18. technical / job-specific skills
communication skills
education / degree
19. technical / job-specific skills
communication skills
motivation
20. technical / job-specific skills
communication skills
problem-solving ability
21. technical / job-specific skills
communication skills
referral / recommendation
22. technical / job-specific skills
education / degree
english / language skills
23. technical / job-specific skills
motivation
education / degree
24. technical / job-specific skills
practical projects / portfolio
education / degree
25. technical / job-specific skills
practical projects / portfolio
internship experience
26. technical / job-specific skills
practical projects / portfolio
problem-solving ability
27. technical / job-specific skills
previous work experience
education / degree
28. technical / job-specific skills
previous work experience
problem-solving ability
29. technical / job-specific skills
problem-solving ability
ability to learn / adaptability

================================================================================
reasons_not_selected
================================================================================
1. insufficient technical / job-specific skills
lack of practical experience
education does not match the position
2. insufficient technical / job-specific skills
lack of practical experience
lack of motivation
3. insufficient technical / job-specific skills
lack of practical experience
lack of previous work experience
4. insufficient technical / job-specific skills
lack of practical experience
poor interview performance
5. insufficient technical / job-specific skills
lack of practical experience
weak communication skills
6. insufficient technical / job-specific skills
lack of previous work experience
weak communication skills
7. insufficient technical / job-specific skills
lack of professionalism
employer needed a more experienced candidate
8. insufficient technical / job-specific skills
poor interview performance
salary expectations
9. insufficient technical / job-specific skills
salary expectations
availability / working hours
10. insufficient technical / job-specific skills
weak communication skills
education does not match the position
11. insufficient technical / job-specific skills
weak communication skills
employer needed a more experienced candidate
12. insufficient technical / job-specific skills
weak communication skills
lack of professionalism
13. insufficient technical / job-specific skills
weak communication skills
location / transportation
14. insufficient technical / job-specific skills
weak communication skills
poor interview performance
15. insufficient technical / job-specific skills
weak english / language skills
lack of professionalism
16. lack of practical experience
education does not match the position
salary expectations
17. lack of practical experience
lack of previous work experience
weak communication skills
18. lack of practical experience
lack of professionalism
location / transportation
19. lack of practical experience
poor interview performance
no relevant portfolio / projects
20. lack of practical experience
weak communication skills
lack of professionalism
21. lack of practical experience
weak english / language skills
lack of motivation
22. lack of previous work experience
lack of professionalism
no relevant portfolio / projects
23. poor interview performance
lack of motivation
lack of long-term commitment
24. poor interview performance
lack of professionalism
lack of long-term commitment
25. poor interview performance
lack of professionalism
lack of motivation
26. weak communication skills
education does not match the position
location / transportation
27. weak communication skills
lack of motivation
lack of long-term commitment
28. weak communication skills
poor interview performance
education does not match the position
29. weak communication skills
poor interview performance
lack of motivation
30. weak communication skills
weak english / language skills
availability / working hours
31. weak communication skills
weak english / language skills
lack of motivation
32. weak communication skills
weak english / language skills
lack of professionalism
33. weak english / language skills
education does not match the position
salary expectations

================================================================================
importance_technical_skills
================================================================================
1. extremely important
2. moderately important
3. not important
4. slightly important
5. very important

================================================================================
importance_practical_experience
================================================================================
1. extremely important
2. moderately important
3. not important
4. slightly important
5. very important

================================================================================
importance_communication
================================================================================
1. extremely important
2. moderately important
3. slightly important
4. very important

================================================================================
importance_problem_solving
================================================================================
1. extremely important
2. moderately important
3. slightly important
4. very important

================================================================================
importance_ability_to_learn
================================================================================
1. extremely important
2. moderately important
3. slightly important
4. very important

================================================================================
importance_degree
================================================================================
1. extremely important
2. moderately important
3. not important
4. slightly important
5. very important

================================================================================
importance_previous_internship
================================================================================
1. extremely important
2. moderately important
3. not important
4. slightly important
5. very important

================================================================================
importance_language_skills
================================================================================
1. extremely important
2. moderately important
3. slightly important
4. very important

================================================================================
entry_level_job_availability
================================================================================
1. it varies significantly by occupation
2. not sure
3. the number of jobs and qualified applicants is roughly balanced
4. there are far more qualified applicants than available jobs
5. there are many more entry-level jobs than qualified young applicants
6. there are somewhat more jobs than qualified applicants
7. there are somewhat more qualified applicants than available jobs

================================================================================
expected_previous_experience
================================================================================
1. 1–2 years
2. 2–3 years
3. depends strongly on the position
4. less than 1 year
5. no experience

================================================================================
response_to_skill_gap
================================================================================
1. consider them for another position
2. depends on the candidate or position
3. hire them and train them internally
4. keep their cv for future opportunities
5. offer a probationary / trial opportunity
6. offer an internship / trainee position
7. reject the candidate

================================================================================
importance_connections
================================================================================
1. extremely important
2. moderately important
3. not important at all
4. slightly important
5. very important
6. we mainly use open / public recruitment processes

================================================================================
university_preference
================================================================================
1. lebanese university graduate
2. no preference
3. private university graduate

================================================================================
unnecessary_requirements
================================================================================
1. depends on the position
2. never
3. not sure
4. often
5. rarely
6. sometimes
7. very often

================================================================================
youth_turnover_reasons
================================================================================
1. better career opportunities
2. better career opportunities
migration / leaving lebanon
3. better career opportunities
migration / leaving lebanon
lack of training or development
4. better career opportunities
migration / leaving lebanon
workload / working hours
5. better career opportunities
personal reasons
6. better career opportunities
working conditions
7. better career opportunities
workload / working hours
8. better career opportunities
workload / working hours
personal reasons
9. better salary elsewhere
10. better salary elsewhere
better career opportunities
lack of career progression
11. better salary elsewhere
better career opportunities
management / workplace culture
12. better salary elsewhere
better career opportunities
migration / leaving lebanon
13. better salary elsewhere
better career opportunities
personal reasons
14. better salary elsewhere
better career opportunities
workload / working hours
15. better salary elsewhere
lack of career progression
lack of training or development
16. better salary elsewhere
migration / leaving lebanon
personal reasons
17. better salary elsewhere
remote opportunities with foreign companies
18. better salary elsewhere
remote opportunities with foreign companies
job instability
19. better salary elsewhere
remote opportunities with foreign companies
migration / leaving lebanon
20. better salary elsewhere

In [9]:
from pandas.api.types import CategoricalDtype

# ============================================================
# ORDERED CATEGORICAL VARIABLES
# ============================================================

# Organization size
df_employer["organization_size"] = df_employer["organization_size"].astype(
    CategoricalDtype(
        categories=[
            "1–10",
            "11–50",
            "51–250",
            "251–500",
            "more than 500"
        ],
        ordered=True
    )
)


# Importance variables
importance_levels = [
    "not important",
    "slightly important",
    "moderately important",
    "very important",
    "extremely important"
]

importance_cols = [
    "importance_technical_skills",
    "importance_practical_experience",
    "importance_communication",
    "importance_problem_solving",
    "importance_ability_to_learn",
    "importance_degree",
    "importance_previous_internship",
    "importance_language_skills"
]

for col in importance_cols:
    df_employer[col] = df_employer[col].astype(
        CategoricalDtype(
            categories=importance_levels,
            ordered=True
        )
    )


# Expected previous experience
df_employer["expected_previous_experience"] = df_employer[
    "expected_previous_experience"
].astype(
    CategoricalDtype(
        categories=[
            "no experience",
            "less than 1 year",
            "1–2 years",
            "2–3 years",
            "depends strongly on the position"
        ],
        ordered=True
    )
)


# Importance of connections
df_employer["importance_connections"] = df_employer[
    "importance_connections"
].astype(
    CategoricalDtype(
        categories=[
            "not important at all",
            "slightly important",
            "moderately important",
            "very important",
            "extremely important",
            "we mainly use open / public recruitment processes"
        ],
        ordered=True
    )
)


# Unnecessary requirements
df_employer["unnecessary_requirements"] = df_employer[
    "unnecessary_requirements"
].astype(
    CategoricalDtype(
        categories=[
            "never",
            "rarely",
            "sometimes",
            "often",
            "very often",
            "not sure",
            "depends on the position"
        ],
        ordered=True
    )
)

In [11]:
# Missing values summary
missing_summary = (
    df_employer.isna()
    .sum()
    .to_frame("missing_count")
)

missing_summary["missing_percentage"] = (
    missing_summary["missing_count"] / len(df_employer) * 100
).round(1)

display(
    missing_summary[
        missing_summary["missing_count"] > 0
    ]
)

                                missing_count  missing_percentage
youth_hired_12m                             3                 8.3
importance_technical_skills                 1                 2.8
importance_ability_to_learn                 1                 2.8
importance_previous_internship              1                 2.8

In [12]:
df_employer["youth_hired_12m"] = (
    df_employer["youth_hired_12m"]
    .cat.add_categories(["none"])
    .fillna("none")
)

In [14]:
import re

multi_choice_cols_employer = [
    "hiring_challenges",
    "recruitment_sources",
    "top_interview_factors",
    "reasons_not_selected",
    "youth_turnover_reasons",
    "employment_improvements"
]

# Choices to exclude from dummy creation
exclude_choices = {
    "we did not experience significant difficulty hiring",
    "we did not have positions to fill"
}

for col in multi_choice_cols_employer:

    choices = set()

    for response in df_employer[col].dropna():
        choices.update(str(response).split("\n"))

    choices = sorted(
        choice.strip()
        for choice in choices
        if choice.strip()
        and choice.strip().lower() not in exclude_choices
    )

    responses = df_employer[col].astype("string").fillna("")

    for choice in choices:

        dummy_name = (
            col + "__" +
            re.sub(r"[^a-zA-Z0-9]+", "_", choice)
            .strip("_")
            .lower()
        )

        df_employer[dummy_name] = (
            responses
            .apply(lambda x: int(choice in x.split("\n")))
            .astype("int8")
        )


# Check created dummy variables
dummy_cols_employer = [
    col for col in df_employer.columns
    if any(
        col.startswith(mc + "__")
        for mc in multi_choice_cols_employer
    )
]

print("Number of dummy variables:", len(dummy_cols_employer))

for col in dummy_cols_employer:
    print(col)

Number of dummy variables: 74
hiring_challenges__candidates_expected_higher_salaries_than_we_could_offer
hiring_challenges__candidates_lacked_the_experience_we_expected
hiring_challenges__candidates_lacked_the_skills_we_needed
hiring_challenges__candidates_were_unavailable_because_of_location_transportation_or_working_hours
hiring_challenges__suitable_candidates_accepted_but_later_left
hiring_challenges__suitable_candidates_declined_our_offers
hiring_challenges__we_received_many_applicants_but_few_met_our_requirements
hiring_challenges__we_received_too_few_applicants
recruitment_sources__direct_applications
recruitment_sources__employee_referrals
recruitment_sources__internships_previous_interns
recruitment_sources__linkedin
recruitment_sources__personal_or_professional_networks
recruitment_sources__public_job_postings_job_platforms
recruitment_sources__recommendations_from_professors_teachers
recruitment_sources__recruitment_agencies
recruitment_sources__social_media
recruitment_sources__universities_career_offices
top_interview_factors__ability_to_learn_adaptability
top_interview_factors__availability_flexibility
top_interview_factors__communication_skills
top_interview_factors__education_degree
top_interview_factors__english_language_skills
top_interview_factors__internship_experience
top_interview_factors__motivation
top_interview_factors__practical_projects_portfolio
top_interview_factors__previous_work_experience
top_interview_factors__problem_solving_ability
top_interview_factors__professional_network
top_interview_factors__professionalism
top_interview_factors__referral_recommendation
top_interview_factors__salary_expectations
top_interview_factors__technical_job_specific_skills
top_interview_factors__university_attended
reasons_not_selected__availability_working_hours
reasons_not_selected__education_does_not_match_the_position
reasons_not_selected__employer_needed_a_more_experienced_candidate
reasons_not_selected__insufficient_technical_job_specific_skills
reasons_not_selected__lack_of_long_term_commitment
reasons_not_selected__lack_of_motivation
reasons_not_selected__lack_of_practical_experience
reasons_not_selected__lack_of_previous_work_experience
reasons_not_selected__lack_of_professionalism
reasons_not_selected__location_transportation
reasons_not_selected__no_relevant_portfolio_projects
reasons_not_selected__poor_interview_performance
reasons_not_selected__salary_expectations
reasons_not_selected__weak_communication_skills
reasons_not_selected__weak_english_language_skills
youth_turnover_reasons__better_career_opportunities
youth_turnover_reasons__better_salary_elsewhere
youth_turnover_reasons__job_instability
youth_turnover_reasons__lack_of_career_progression
youth_turnover_reasons__lack_of_training_or_development
youth_turnover_reasons__management_workplace_culture
youth_turnover_reasons__migration_leaving_lebanon
youth_turnover_reasons__personal_reasons
youth_turnover_reasons__remote_opportunities_with_foreign_companies
youth_turnover_reasons__we_have_not_experienced_significant_turnover
youth_turnover_reasons__working_conditions
youth_turnover_reasons__workload_working_hours
employment_improvements__better_salaries_compensation
employment_improvements__better_working_conditions
employment_improvements__career_guidance
employment_improvements__employer_linked_training
employment_improvements__entrepreneurship_support
employment_improvements__government_incentives_for_employers
employment_improvements__internships_apprenticeships
employment_improvements__interview_preparation
employment_improvements__job_placement_job_matching
employment_improvements__job_specific_training
employment_improvements__mentorship
employment_improvements__professional_networking_opportunities
employment_improvements__university_employer_partnerships

In [ ]:
#start of descriptive statistics

In [15]:
def categorical_summary(df, col):
    summary = (
        df[col]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="frequency")
    )

    summary["percentage"] = (
        summary["frequency"] / len(df) * 100
    ).round(1)

    return summary


profile_vars_employer = [
    "industry",
    "organization_size",
    "hiring_role",
    "youth_hired_12m"
]

for col in profile_vars_employer:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)
    display(categorical_summary(df_employer, col))

================================================================================
industry
================================================================================

                           category  frequency  percentage
0                   technology / it         12        33.3
1  professional / business services          7        19.4
2                         education          4        11.1
3           marketing / advertising          3         8.3
4                             other          3         8.3
5        engineering / construction          2         5.6
6                 finance / banking          2         5.6
7          manufacturing / industry          1         2.8
8                        healthcare          1         2.8
9       hospitality / tourism / f&b          1         2.8

================================================================================
organization_size
================================================================================

        category  frequency  percentage
0          11–50         11        30.6
1         51–250         11        30.6
2           1–10          9        25.0
3  more than 500          4        11.1
4        251–500          1         2.8

================================================================================
hiring_role
================================================================================

                     category  frequency  percentage
0             department head         12        33.3
1            hr / recruitment          8        22.2
2  hiring manager / team lead          7        19.4
3             owner / founder          7        19.4
4                       other          2         5.6

================================================================================
youth_hired_12m
================================================================================

       category  frequency  percentage
0           3–5         14        38.9
1  more than 10         12        33.3
2          6–10          4        11.1
3           1–2          3         8.3
4          none          3         8.3

In [16]:
challenge_cols = [
    col for col in df_employer.columns
    if col.startswith("hiring_challenges__")
]

challenge_summary = pd.DataFrame({
    "challenge": [
        col.replace("hiring_challenges__", "").replace("_", " ")
        for col in challenge_cols
    ],
    "frequency": [
        df_employer[col].sum()
        for col in challenge_cols
    ]
})

challenge_summary["percentage"] = (
    challenge_summary["frequency"] / len(df_employer) * 100
).round(1)

challenge_summary = challenge_summary.sort_values(
    "frequency", ascending=False
).reset_index(drop=True)

display(challenge_summary)

                                           challenge  frequency  percentage
0  we received many applicants but few met our re...         25        69.4
1       candidates lacked the experience we expected         18        50.0
2             candidates lacked the skills we needed         16        44.4
3  candidates expected higher salaries than we co...         16        44.4
4            suitable candidates declined our offers         11        30.6
5  candidates were unavailable because of locatio...          9        25.0
6        suitable candidates accepted but later left          5        13.9
7                     we received too few applicants          2         5.6

In [17]:
source_cols = [
    col for col in df_employer.columns
    if col.startswith("recruitment_sources__")
]

source_summary = pd.DataFrame({
    "source": [
        col.replace("recruitment_sources__", "").replace("_", " ")
        for col in source_cols
    ],
    "frequency": [
        df_employer[col].sum()
        for col in source_cols
    ]
})

source_summary["percentage"] = (
    source_summary["frequency"] / len(df_employer) * 100
).round(1)

source_summary = source_summary.sort_values(
    "frequency", ascending=False
).reset_index(drop=True)

display(source_summary)

                                     source  frequency  percentage
0                                  linkedin         24        66.7
1                        employee referrals         16        44.4
2                       direct applications         14        38.9
3         personal or professional networks         13        36.1
4                              social media         13        36.1
5         public job postings job platforms         12        33.3
6               universities career offices         11        30.6
7              internships previous interns          5        13.9
8  recommendations from professors teachers          4        11.1
9                      recruitment agencies          3         8.3

In [18]:
import pandas as pd

# ============================================================
# HIRING CHALLENGES — DESCRIPTIVE SUMMARY
# ============================================================

challenge_cols = [
    col for col in df_employer.columns
    if col.startswith("hiring_challenges__")
]

challenge_summary = pd.DataFrame({
    "challenge": [
        col.replace("hiring_challenges__", "").replace("_", " ")
        for col in challenge_cols
    ],
    "frequency": [
        df_employer[col].sum()
        for col in challenge_cols
    ]
})

challenge_summary["percentage"] = (
    challenge_summary["frequency"] / len(df_employer) * 100
).round(1)

challenge_summary = (
    challenge_summary
    .sort_values("frequency", ascending=False)
    .reset_index(drop=True)
)

display(challenge_summary)

                                           challenge  frequency  percentage
0  we received many applicants but few met our re...         25        69.4
1       candidates lacked the experience we expected         18        50.0
2             candidates lacked the skills we needed         16        44.4
3  candidates expected higher salaries than we co...         16        44.4
4            suitable candidates declined our offers         11        30.6
5  candidates were unavailable because of locatio...          9        25.0
6        suitable candidates accepted but later left          5        13.9
7                     we received too few applicants          2         5.6

In [19]:
# ============================================================
# WHAT EMPLOYERS LOOK FOR
# ============================================================

def dummy_summary(df, prefix):
    
    cols = [
        col for col in df.columns
        if col.startswith(prefix + "__")
    ]

    summary = pd.DataFrame({
        "category": [
            col.replace(prefix + "__", "").replace("_", " ")
            for col in cols
        ],
        "frequency": [
            df[col].sum()
            for col in cols
        ]
    })

    summary["percentage"] = (
        summary["frequency"] / len(df) * 100
    ).round(1)

    return (
        summary
        .sort_values("frequency", ascending=False)
        .reset_index(drop=True)
    )


# ------------------------------------------------------------
# 1. Top factors employers consider when interviewing
# ------------------------------------------------------------

print("=" * 80)
print("TOP INTERVIEW FACTORS")
print("=" * 80)

top_factors_summary = dummy_summary(
    df_employer,
    "top_interview_factors"
)

display(top_factors_summary)


# ------------------------------------------------------------
# 2. Reasons young applicants are not selected
# ------------------------------------------------------------

print("=" * 80)
print("REASONS NOT SELECTED")
print("=" * 80)

reasons_summary = dummy_summary(
    df_employer,
    "reasons_not_selected"
)

display(reasons_summary)

================================================================================
TOP INTERVIEW FACTORS
================================================================================

                         category  frequency  percentage
0            communication skills         21        58.3
1   technical job specific skills         20        55.6
2         problem solving ability         12        33.3
3                education degree         10        27.8
4                      motivation         10        27.8
5   ability to learn adaptability          9        25.0
6        previous work experience          6        16.7
7    practical projects portfolio          4        11.1
8                 professionalism          4        11.1
9         referral recommendation          3         8.3
10          internship experience          3         8.3
11        english language skills          2         5.6
12       availability flexibility          1         2.8
13           professional network          1         2.8
14            salary expectations          1         2.8
15            university attended          1         2.8

================================================================================
REASONS NOT SELECTED
================================================================================

                                        category  frequency  percentage
0                      weak communication skills         18        50.0
1     insufficient technical job specific skills         16        44.4
2                   lack of practical experience         14        38.9
3                        lack of professionalism         10        27.8
4                     poor interview performance          9        25.0
5                             lack of motivation          7        19.4
6          education does not match the position          6        16.7
7                   weak english language skills          6        16.7
8               lack of previous work experience          6        16.7
9                            salary expectations          4        11.1
10                  lack of long term commitment          3         8.3
11                       location transportation          3         8.3
12  employer needed a more experienced candidate          2         5.6
13                    availability working hours          2         5.6
14                no relevant portfolio projects          2         5.6

In [21]:
# ============================================================
# STEP 5 — IMPORTANCE RATINGS
# ============================================================

importance_vars = [
    "importance_technical_skills",
    "importance_practical_experience",
    "importance_communication",
    "importance_problem_solving",
    "importance_ability_to_learn",
    "importance_degree",
    "importance_previous_internship",
    "importance_language_skills"
]

# Order of the Likert scale
importance_order = [
    "not important",
    "slightly important",
    "moderately important",
    "very important",
    "extremely important"
]

# Numeric mapping used ONLY temporarily for median
importance_numeric = {
    "not important": 1,
    "slightly important": 2,
    "moderately important": 3,
    "very important": 4,
    "extremely important": 5
}

for col in importance_vars:

    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)

    # --------------------------------------------------------
    # Frequency and percentage
    # --------------------------------------------------------

    summary = (
        df_employer[col]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="frequency")
    )

    summary["percentage"] = (
        summary["frequency"] / len(df_employer) * 100
    ).round(1)

    # Order categories correctly
    summary["category"] = pd.Categorical(
        summary["category"],
        categories=importance_order,
        ordered=True
    )

    summary = (
        summary
        .sort_values("category")
        .reset_index(drop=True)
    )

    display(summary)

    # --------------------------------------------------------
    # Temporary numeric conversion ONLY for median
    # Does NOT modify df_employer
    # --------------------------------------------------------

    temp_numeric = (
        df_employer[col]
        .map(importance_numeric)
        .astype("float")
    )

    print("Median:", temp_numeric.median())

================================================================================
importance_technical_skills
================================================================================

               category  frequency  percentage
0         not important          2         5.6
1    slightly important          4        11.1
2  moderately important          8        22.2
3        very important         11        30.6
4   extremely important         10        27.8
5                   NaN          1         2.8

Median: 4.0

================================================================================
importance_practical_experience
================================================================================

               category  frequency  percentage
0         not important          2         5.6
1    slightly important          5        13.9
2  moderately important         16        44.4
3        very important          8        22.2
4   extremely important          5        13.9

Median: 3.0

================================================================================
importance_communication
================================================================================

               category  frequency  percentage
0         not important          0         0.0
1    slightly important          3         8.3
2  moderately important          7        19.4
3        very important         11        30.6
4   extremely important         15        41.7

Median: 4.0

================================================================================
importance_problem_solving
================================================================================

               category  frequency  percentage
0         not important          0         0.0
1    slightly important          4        11.1
2  moderately important         11        30.6
3        very important         11        30.6
4   extremely important         10        27.8

Median: 4.0

================================================================================
importance_ability_to_learn
================================================================================

               category  frequency  percentage
0         not important          0         0.0
1    slightly important          1         2.8
2  moderately important          3         8.3
3        very important          7        19.4
4   extremely important         24        66.7
5                   NaN          1         2.8

Median: 5.0

================================================================================
importance_degree
================================================================================

               category  frequency  percentage
0         not important          2         5.6
1    slightly important          7        19.4
2  moderately important         13        36.1
3        very important         12        33.3
4   extremely important          2         5.6

Median: 3.0

================================================================================
importance_previous_internship
================================================================================

               category  frequency  percentage
0         not important          5        13.9
1    slightly important         11        30.6
2  moderately important         12        33.3
3        very important          4        11.1
4   extremely important          3         8.3
5                   NaN          1         2.8

Median: 3.0

================================================================================
importance_language_skills
================================================================================

               category  frequency  percentage
0         not important          0         0.0
1    slightly important          4        11.1
2  moderately important          9        25.0
3        very important         14        38.9
4   extremely important          9        25.0

Median: 4.0

In [22]:
# ============================================================
# STEP 6 — ENTRY-LEVEL HIRING CONDITIONS
# ============================================================

entry_level_vars = [
    "entry_level_job_availability",
    "expected_previous_experience",
    "unnecessary_requirements"
]

for col in entry_level_vars:

    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)

    summary = (
        df_employer[col]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="frequency")
    )

    summary["percentage"] = (
        summary["frequency"] / len(df_employer) * 100
    ).round(1)

    display(summary)

================================================================================
entry_level_job_availability
================================================================================

                                            category  frequency  percentage
0              it varies significantly by occupation          9        25.0
1  there are somewhat more jobs than qualified ap...          6        16.7
2  there are somewhat more qualified applicants t...          6        16.7
3  there are far more qualified applicants than a...          5        13.9
4  the number of jobs and qualified applicants is...          4        11.1
5                                           not sure          3         8.3
6  there are many more entry-level jobs than qual...          3         8.3

================================================================================
expected_previous_experience
================================================================================

                           category  frequency  percentage
0                  less than 1 year         11        30.6
1                         1–2 years          9        25.0
2                     no experience          6        16.7
3  depends strongly on the position          6        16.7
4                         2–3 years          4        11.1

================================================================================
unnecessary_requirements
================================================================================

                  category  frequency  percentage
0                sometimes         13        36.1
1  depends on the position          7        19.4
2                    often          6        16.7
3               very often          4        11.1
4                   rarely          3         8.3
5                 not sure          2         5.6
6                    never          1         2.8

In [23]:
# ============================================================
# STEP 7 — EMPLOYER RESPONSE TO SKILL GAPS & ACCESS TO JOBS
# ============================================================

step7_vars = [
    "response_to_skill_gap",
    "importance_connections",
    "university_preference"
]

for col in step7_vars:

    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)

    summary = (
        df_employer[col]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="frequency")
    )

    summary["percentage"] = (
        summary["frequency"] / len(df_employer) * 100
    ).round(1)

    display(summary)

================================================================================
response_to_skill_gap
================================================================================

                                   category  frequency  percentage
0       hire them and train them internally          8        22.2
1      depends on the candidate or position          7        19.4
2    keep their cv for future opportunities          6        16.7
3                      reject the candidate          5        13.9
4  offer a probationary / trial opportunity          4        11.1
5    offer an internship / trainee position          4        11.1
6        consider them for another position          2         5.6

================================================================================
importance_connections
================================================================================

                                            category  frequency  percentage
0                                     very important         12        33.3
1                               moderately important          7        19.4
2                                extremely important          7        19.4
3                                 slightly important          5        13.9
4  we mainly use open / public recruitment processes          4        11.1
5                               not important at all          1         2.8

================================================================================
university_preference
================================================================================

                       category  frequency  percentage
0                 no preference         26        72.2
1  lebanese university graduate          6        16.7
2   private university graduate          4        11.1

In [24]:
# ============================================================
# STEP 8 — YOUTH TURNOVER REASONS
# ============================================================

turnover_dummy_cols = [
    col for col in df_employer.columns
    if col.startswith("youth_turnover_reasons__")
]

turnover_summary = []

for col in turnover_dummy_cols:

    frequency = df_employer[col].sum()
    percentage = (frequency / len(df_employer) * 100).round(1)

    # Make the label readable
    label = col.replace("youth_turnover_reasons__", "").replace("_", " ")

    turnover_summary.append({
        "reason": label,
        "frequency": frequency,
        "percentage": percentage
    })

turnover_summary = (
    pd.DataFrame(turnover_summary)
    .sort_values("frequency", ascending=False)
    .reset_index(drop=True)
)

display(turnover_summary)

                                          reason  frequency  percentage
0                        better salary elsewhere         17        47.2
1                    better career opportunities         15        41.7
2                      migration leaving lebanon         11        30.6
3                         workload working hours          7        19.4
4   we have not experienced significant turnover          7        19.4
5    remote opportunities with foreign companies          7        19.4
6                               personal reasons          6        16.7
7                                job instability          3         8.3
8                     lack of career progression          3         8.3
9                lack of training or development          2         5.6
10                            working conditions          2         5.6
11                  management workplace culture          1         2.8

In [25]:
# ============================================================
# STEP 9 — EMPLOYMENT IMPROVEMENTS
# ============================================================

improvement_dummy_cols = [
    col for col in df_employer.columns
    if col.startswith("employment_improvements__")
]

improvement_summary = []

for col in improvement_dummy_cols:

    frequency = df_employer[col].sum()
    percentage = (frequency / len(df_employer) * 100).round(1)

    # Make the label readable
    label = (
        col
        .replace("employment_improvements__", "")
        .replace("_", " ")
    )

    improvement_summary.append({
        "improvement": label,
        "frequency": frequency,
        "percentage": percentage
    })

improvement_summary = (
    pd.DataFrame(improvement_summary)
    .sort_values("frequency", ascending=False)
    .reset_index(drop=True)
)

display(improvement_summary)

                              improvement  frequency  percentage
0            better salaries compensation         15        41.7
1                         career guidance         13        36.1
2             internships apprenticeships         11        30.6
3        university employer partnerships         10        27.8
4                   job specific training          9        25.0
5                              mentorship          9        25.0
6   professional networking opportunities          8        22.2
7               better working conditions          5        13.9
8                   interview preparation          5        13.9
9              job placement job matching          5        13.9
10               employer linked training          3         8.3
11    government incentives for employers          3         8.3
12               entrepreneurship support          2         5.6

In [26]:
#save the cleaned dataset to a new Excel file
output_path = r"C:\Users\User\Desktop\youth unemployement\Cleaned_Employers_Perspectives_on_Youth_Unemployment.xlsx"
df_employer.to_excel(output_path, index=False)