In [1]:
import pandas as pd
import numpy as np

# ============================================================
# 1. LOAD YOUTH DATA
# ============================================================

file_path = r"C:\Users\User\Desktop\youth unemployement\youth_form.xlsx"   # Change to your actual file

# Excel
df_youth = pd.read_excel(file_path)

In [2]:
#explore the data

In [3]:
print("=" * 80)
print("YOUTH DATASET OVERVIEW")
print("=" * 80)

print(f"Number of respondents: {df_youth.shape[0]}")
print(f"Number of features/columns: {df_youth.shape[1]}")

================================================================================
YOUTH DATASET OVERVIEW
================================================================================
Number of respondents: 83
Number of features/columns: 30

In [4]:
print("\n" + "=" * 80)
print("FIRST 5 RESPONSES")
print("=" * 80)

display(df_youth.head())

================================================================================
FIRST 5 RESPONSES
================================================================================

,Submission Date,What is the highest level of education or training you have completed? ما هو أعلى مستوى من التعليم أو التدريب الذي أكملته؟,What is your main field of study or professional specialization? ما هو مجال دراستك الرئيسي أو تخصصك المهني؟,Which of the following best describes your current situation? أي من الخيارات التالية يصف وضعك الحالي بشكل أفضل؟,"What factors, if any, make it difficult for you to find or obtain a job? ما هي العوامل التي تجعل من الصعب عليك العثور على وظيفة أو الحصول عليها، إن وُجدت؟",How long have you been looking for a suitable employment opportunity? منذ متى وأنت تبحث عن فرصة عمل مناسبة؟,Approximately how many job applications have you submitted during the past 3 months? تقريبًا، كم عدد طلبات التوظيف التي قدمتها خلال الأشهر الثلاثة الماضية؟,"When you hear about a suitable job opportunity, where are you most likely to hear about it? عندما تسمع عن فرصة عمل مناسبة، أين يُرجح أن تسمع عنها؟",Which ONE of these is the biggest difficulty for you? أي واحد من هذه العوامل يمثل أكبر صعوبة بالنسبة لك؟,"Thinking about your recent job search, at which stage do you face the greatest difficulty? بالتفكير في بحثك الأخير عن عمل، في أي مرحلة تواجه أكبر صعوبة؟",...,"When you are rejected from a job, how often do employers provide a reason or feedback? عندما يتم رفضك في وظيفة، كم مرة يقدم أصحاب العمل سببًا للرفض أو ملاحظات حول طلبك؟",To what extent has the security situation in Lebanon affected your ability to find or obtain a job? إلى أي مدى أثّر الوضع الأمني في لبنان على قدرتك على العثور على وظيفة أو الحصول عليها؟,Which aspects of available jobs in Lebanon would make you less likely to accept a position? ما هي جوانب الوظائف المتاحة في لبنان التي قد تجعلك أقل احتمالًا لقبول وظيفة؟,"If you found a job related to your skills but the salary did not cover your basic living costs, what would you most likely do? إذا وجدت وظيفة مرتبطة بمهاراتك، ولكن الراتب لا يغطي تكاليف معيشتك الأساسية، فما الذي يُرجح أن تفعله؟","Which statement best describes your access to modern work opportunities such as remote work, freelancing, digital jobs, or international online work? أي من العبارات التالية تصف بشكل أفضل مدى وصولك إلى فرص العمل الحديثة، مثل العمل عن بُعد، والعمل الحر، والوظائف الرقمية، أو العمل عبر الإنترنت مع جهات دولية؟","If you had a realistic opportunity to work abroad in your field, what would you most likely choose? إذا أتيحت لك فرصة واقعية للعمل في الخارج في مجال تخصصك، فما الخيار الذي يُرجح أن تختاره؟",What are the main reasons you would consider working abroad? ما هي الأسباب الرئيسية التي قد تدفعك إلى التفكير في العمل في الخارج؟,Which types of support would most improve your chances of finding a suitable employment opportunity? ما أنواع الدعم التي من شأنها تحسين فرصك في العثور على فرصة عمل مناسبة بشكل أكبر؟,"If an organization in Lebanon could provide ONE service to help you access better employment opportunities, which would be most valuable to you? إذا كان بإمكان منظمة في لبنان تقديم خدمة واحدة لمساعدتك في الوصول إلى فرص عمل أفضل، فما الخدمة التي ستكون الأكثر قيمة بالنسبة لك؟","In your opinion, what is the biggest change that would make it easier for young people in Lebanon to find and build a sustainable career? برأيك، ما هو التغيير الأكبر الذي من شأنه أن يجعل من الأسهل على الشباب في لبنان العثور على عمل وبناء مسيرة مهنية مستدامة؟"
0,"Aug 31, 2026",Bachelor’s degree,Graphic design,I am currently unemployed and actively looking...,High competition for available positions\nLack...,Less than 3 months,More than 20,Personal or professional connections,Lack of professional connections / networks,Receiving a job offer,...,Almost never,Significantly,Low salary\nSalary does not cover basic living...,Continue searching for a better-paying job,I know about them but do not know how to acces...,Move abroad permanently,Higher salary\nBetter career opportunities\nBe...,Paid internship / practical work experience\nT...,Paid internship or work experience,More accessible entry-level jobs and paid inte...
1,"Aug 31, 2026",Bachelor’s degree,BMIS,"I am working, but my current work does not pro...",High competition for available positions\nLack...,More than 1 year,1–5,Online job platforms / websites\nLinkedIn or p...,Lack of practical work experience,Getting invited to interviews,...,Rarely,Significantly,Lack of training or learning opportunities,Work two or more jobs,I lack the skills needed,Stay if I can find a suitable opportunity locally,Higher salary\nBetter career opportunities\nEc...,Paid internship / practical work experience\nT...,Paid internship or work experience,"In my opinion, a chance to get an Internship i..."
2,"Aug 31, 2026",Bachelor’s degree,Dentistry,Other,High competition for available positions,I am not currently looking,NaN,Online job platforms / websites\nSocial media\...,High competition for available positions,I have not yet reached any of these stages,...,Almost never,Significantly,Lack of benefits,Negotiate for a higher salary or better benefits,I have access and have already used these oppo...,Stay if I can find a suitable opportunity locally,Higher salary\nBetter career opportunities,Paid internship / practical work experience\nD...,Career guidance and job matching,.
3,"Aug 31, 2026",Bachelor’s degree,Designer,I am currently unemployed and actively looking...,Location of available jobs / distance from whe...,3–6 months,11–20,Online job platforms / websites,Location / transportation,Getting invited to interviews,...,I usually do not receive a response,Slightly,Low salary\nSalary does not cover basic living...,Accept the job temporarily,I do not know enough about these opportunities,Work abroad temporarily and return later,Higher salary\nLack of suitable opportunities ...,Paid internship / practical work experience,Paid internship or work experience,Just for it to be easier to find something imm...
4,"Aug 31, 2026",Doctorate / PhD,Data science,I am currently unemployed and actively looking...,High competition for available positions\nLack...,More than 2 years,More than 20,LinkedIn or professional platforms,High competition for available positions,Receiving a job offer,...,Almost never,Very significantly,Salary does not cover basic living costs\nPoor...,Rely on family support while searching,I lack the skills needed,Work abroad temporarily and return later,Higher salary\nBetter career opportunities\nMo...,Technical / job-specific skills training\nSoft...,Job-specific skills training,NaN

In [5]:
print(len(df_youth.columns))

for i, col in enumerate(df_youth.columns):
    print(i, ":", col)

30
0 : Submission Date
1 : What is the highest level of education or training you have completed? ما هو أعلى مستوى من التعليم أو التدريب الذي أكملته؟
2 : What is your main field of study or professional specialization? ما هو مجال دراستك الرئيسي أو تخصصك المهني؟
3 : Which of the following best describes your current situation? أي من الخيارات التالية يصف وضعك الحالي بشكل أفضل؟
4 : What factors, if any, make it difficult for you to find or obtain a job? ما هي العوامل التي تجعل من الصعب عليك العثور على وظيفة أو الحصول عليها، إن وُجدت؟
5 : How long have you been looking for a suitable employment opportunity? منذ متى وأنت تبحث عن فرصة عمل مناسبة؟
6 : Approximately how many job applications have you submitted during the past 3 months? تقريبًا، كم عدد طلبات التوظيف التي قدمتها خلال الأشهر الثلاثة الماضية؟
7 : When you hear about a suitable job opportunity, where are you most likely to hear about it?  عندما تسمع عن فرصة عمل مناسبة، أين يُرجح أن تسمع عنها؟
8 : Which ONE of these is the biggest difficulty for you? أي واحد من هذه العوامل يمثل أكبر صعوبة بالنسبة لك؟
9 : Thinking about your recent job search, at which stage do you face the greatest difficulty? بالتفكير في بحثك الأخير عن عمل، في أي مرحلة تواجه أكبر صعوبة؟
10 : After submitting applications, what usually happens? بعد تقديم طلبات التوظيف، ماذا يحدث عادةً؟
11 : How often have you encountered job opportunities that required previous work experience that you did not yet have? كم مرة واجهت فرص عمل كانت تتطلب خبرة سابقة لم تكن لديك بعد؟
12 : How important do you think personal or professional connections are for getting a job in Lebanon? ما مدى أهمية العلاقات الشخصية أو المهنية، برأيك، للحصول على وظيفة في لبنان؟
13 : Have you ever felt that you needed a personal connection or referral to access a job opportunity? هل شعرت يومًا أنك بحاجة إلى علاقة شخصية أو توصية من شخص ما للوصول إلى فرصة عمل؟
14 : How well do you feel your education or training has prepared you for the jobs you are currently seeking? إلى أي مدى تشعر أن تعليمك أو تدريبك قد أعدّك للوظائف التي تبحث عنها حاليًا؟
15 : If you feel unprepared, what skills or knowledge do you feel you are missing? إذا كنت تشعر بأنك غير مستعد، فما المهارات أو المعارف التي تشعر أنك تفتقر إليها؟
16 : How often do you see entry-level opportunities requiring more experience than you currently have? كم مرة ترى فرص عمل للمبتدئين تتطلب خبرة أكبر من الخبرة التي تمتلكها حاليًا؟
17 : Have you ever reached an interview stage but not received an offer afterward? هل سبق أن وصلت إلى مرحلة المقابلة ولكن لم تحصل على عرض عمل بعدها؟
18 : If you have attended job interviews, what do you find most difficult? إذا سبق لك حضور مقابلات عمل، فما أكثر الأمور التي تجدها صعوبة؟
19 : After being repeatedly rejected from jobs, how does it affect your willingness to continue applying for other jobs? بعد التعرض للرفض المتكرر من الوظائف، كيف يؤثر ذلك على استعدادك للاستمرار في التقدم إلى وظائف أخرى؟
20 : When you are rejected from a job, how often do employers provide a reason or feedback? عندما يتم رفضك في وظيفة، كم مرة يقدم أصحاب العمل سببًا للرفض أو ملاحظات حول طلبك؟
21 : To what extent has the security situation in Lebanon affected your ability to find or obtain a job? إلى أي مدى أثّر الوضع الأمني في لبنان على قدرتك على العثور على وظيفة أو الحصول عليها؟
22 : Which aspects of available jobs in Lebanon would make you less likely to accept a position? ما هي جوانب الوظائف المتاحة في لبنان التي قد تجعلك أقل احتمالًا لقبول وظيفة؟
23 : If you found a job related to your skills but the salary did not cover your basic living costs, what would you most likely do? إذا وجدت وظيفة مرتبطة بمهاراتك، ولكن الراتب لا يغطي تكاليف معيشتك الأساسية، فما الذي يُرجح أن تفعله؟
24 : Which statement best describes your access to modern work opportunities such as remote work, freelancing, digital jobs, or international online work?                              أي من العبارات التالية تصف بشكل أفضل مدى وصولك إلى فرص العمل الحديثة، مثل العمل عن بُعد، والعمل الحر، والوظائف الرقمية، أو العمل عبر الإنترنت مع جهات دولية؟
25 : If you had a realistic opportunity to work abroad in your field, what would you most likely choose?                                                                                                                                                              إذا أتيحت لك فرصة واقعية للعمل في الخارج في مجال تخصصك، فما الخيار الذي يُرجح أن تختاره؟
26 : What are the main reasons you would consider working abroad?                                                                     ما هي الأسباب الرئيسية التي قد تدفعك إلى التفكير في العمل في الخارج؟
27 : Which types of support would most improve your chances of finding a suitable employment opportunity?                                                                                                                               ما أنواع الدعم التي من شأنها تحسين فرصك في العثور على فرصة عمل مناسبة بشكل أكبر؟
28 : If an organization in Lebanon could provide ONE service to help you access better employment opportunities, which would be most valuable to you?                                              إذا كان بإمكان منظمة في لبنان تقديم خدمة واحدة لمساعدتك في الوصول إلى فرص عمل أفضل، فما الخدمة التي ستكون الأكثر قيمة بالنسبة لك؟
29 : In your opinion, what is the biggest change that would make it easier for young people in Lebanon to find and build a sustainable career?                                                           برأيك، ما هو التغيير الأكبر الذي من شأنه أن يجعل من الأسهل على الشباب في لبنان العثور على عمل وبناء مسيرة مهنية مستدامة؟

In [6]:
# ============================================================
# RENAME YOUTH DATASET COLUMNS
# ============================================================

new_names = [
    "submission_date",             # 0
    "education_level",             # 1
    "field_of_study",              # 2
    "current_status",              # 3
    "job_search_barriers",         # 4
    "job_search_duration",         # 5
    "applications_3m",             # 6
    "job_opportunity_source",      # 7
    "biggest_difficulty",          # 8
    "difficult_job_search_stage",  # 9
    "application_outcome",        # 10
    "experience_requirement",      # 11
    "importance_connections",      # 12
    "needed_connection",           # 13
    "education_job_preparation",   # 14
    "missing_skills",              # 15
    "entry_level_experience",      # 16
    "interview_without_offer",     # 17
    "interview_difficulties",      # 18
    "rejection_effect",            # 19
    "employer_feedback",           # 20
    "security_impact",             # 21
    "job_acceptance_barriers",     # 22
    "low_salary_response",         # 23
    "modern_work_access",          # 24
    "work_abroad_preference",      # 25
    "reasons_work_abroad",         # 26
    "employment_support",          # 27
    "most_valuable_service",       # 28
    "needed_systemic_change"       # 29
]

# Check that the number of names matches the number of columns
print("Number of columns:", len(df_youth.columns))
print("Number of new names:", len(new_names))

if len(df_youth.columns) == len(new_names):
    df_youth.columns = new_names
    print("\nColumns renamed successfully!")
else:
    print("\nERROR: Number of names does not match number of columns.")

Number of columns: 30
Number of new names: 30

Columns renamed successfully!

In [7]:
df_youth = df_youth.drop(columns=["submission_date"])

In [8]:
# Create unique ID for each youth respondent
df_youth.insert(
    0,
    "youth_id",
    ["Y{:03d}".format(i) for i in range(1, len(df_youth) + 1)]
)

# Check
print(df_youth[["youth_id"]].head(10))
print("Number of unique IDs:", df_youth["youth_id"].nunique())

  youth_id
0     Y001
1     Y002
2     Y003
3     Y004
4     Y005
5     Y006
6     Y007
7     Y008
8     Y009
9     Y010
Number of unique IDs: 83

In [9]:
# ------------------------------------------------------------
# 1. COLUMN NAMES
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("ALL FEATURES / QUESTIONS")
print("=" * 80)

for i, col in enumerate(df_youth.columns, 1):
    print(f"{i}. {col}")

================================================================================
ALL FEATURES / QUESTIONS
================================================================================
1. youth_id
2. education_level
3. field_of_study
4. current_status
5. job_search_barriers
6. job_search_duration
7. applications_3m
8. job_opportunity_source
9. biggest_difficulty
10. difficult_job_search_stage
11. application_outcome
12. experience_requirement
13. importance_connections
14. needed_connection
15. education_job_preparation
16. missing_skills
17. entry_level_experience
18. interview_without_offer
19. interview_difficulties
20. rejection_effect
21. employer_feedback
22. security_impact
23. job_acceptance_barriers
24. low_salary_response
25. modern_work_access
26. work_abroad_preference
27. reasons_work_abroad
28. employment_support
29. most_valuable_service
30. needed_systemic_change

In [10]:
# Reorder columns
cols = [
    "youth_id",
    "education_level",
    "field_of_study",
    "current_status",
    "job_search_duration",
    "applications_3m",
    "job_opportunity_source",
    "job_search_barriers",
    "biggest_difficulty",
    "difficult_job_search_stage",
    "application_outcome",
    "experience_requirement",
    "importance_connections",
    "needed_connection",
    "education_job_preparation",
    "missing_skills",
    "entry_level_experience",
    "interview_without_offer",
    "interview_difficulties",
    "rejection_effect",
    "employer_feedback",
    "security_impact",
    "job_acceptance_barriers",
    "low_salary_response",
    "modern_work_access",
    "work_abroad_preference",
    "reasons_work_abroad",
    "employment_support",
    "most_valuable_service",
    "needed_systemic_change"
]

df_youth = df_youth[cols]

# Verify order
for i, col in enumerate(df_youth.columns, 1):
    print(f"{i}. {col}")

1. youth_id
2. education_level
3. field_of_study
4. current_status
5. job_search_duration
6. applications_3m
7. job_opportunity_source
8. job_search_barriers
9. biggest_difficulty
10. difficult_job_search_stage
11. application_outcome
12. experience_requirement
13. importance_connections
14. needed_connection
15. education_job_preparation
16. missing_skills
17. entry_level_experience
18. interview_without_offer
19. interview_difficulties
20. rejection_effect
21. employer_feedback
22. security_impact
23. job_acceptance_barriers
24. low_salary_response
25. modern_work_access
26. work_abroad_preference
27. reasons_work_abroad
28. employment_support
29. most_valuable_service
30. needed_systemic_change

In [11]:
# ============================================================
# 5. GENERAL COLUMN SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("COLUMN SUMMARY")
print("=" * 80)

summary = pd.DataFrame({
    "Feature": df_youth.columns,
    "Data Type": df_youth.dtypes.astype(str).values,
    "Missing": df_youth.isna().sum().values,
    "Missing %": (df_youth.isna().mean() * 100).round(2).values,
    "Number of Choices": df_youth.nunique(dropna=True).values
})

display(summary)

================================================================================
COLUMN SUMMARY
================================================================================

,Feature,Data Type,Missing,Missing %,Number of Choices
0,youth_id,object,0,0.00,83
1,education_level,object,0,0.00,5
2,field_of_study,object,1,1.20,68
3,current_status,object,0,0.00,5
4,job_search_duration,object,0,0.00,6
5,applications_3m,object,21,25.30,4
6,job_opportunity_source,object,0,0.00,47
7,job_search_barriers,object,0,0.00,59
8,biggest_difficulty,object,0,0.00,10
9,difficult_job_search_stage,object,0,0.00,9
10,application_outcome,object,0,0.00,6
11,experience_requirement,object,0,0.00,6
12,importance_connections,object,0,0.00,6
13,needed_connection,object,0,0.00,5
14,education_job_preparation,object,0,0.00,6
15,missing_skills,object,0,0.00,45
16,entry_level_experience,object,0,0.00,6
17,interview_without_offer,object,0,0.00,6
18,interview_difficulties,object,0,0.00,38
19,rejection_effect,object,0,0.00,5
20,employer_feedback,object,0,0.00,5
21,security_impact,object,0,0.00,5
22,job_acceptance_barriers,object,0,0.00,62
23,low_salary_response,object,0,0.00,8
24,modern_work_access,object,0,0.00,7
25,work_abroad_preference,object,0,0.00,6
26,reasons_work_abroad,object,0,0.00,55
27,employment_support,object,0,0.00,59
28,most_valuable_service,object,0,0.00,11
29,needed_systemic_change,object,22,26.51,59

In [12]:

# ============================================================
# 6. CHOICES / CLASSES FOR EACH FEATURE
# ============================================================

print("\n" + "=" * 80)
print("CHOICES / CLASSES FOR EACH FEATURE")
print("=" * 80)

for i, col in enumerate(df_youth.columns, 1):

    print("\n" + "-" * 80)
    print(f"{i}. {col}")
    print("-" * 80)

    print(f"Data type: {df_youth[col].dtype}")
    print(f"Number of choices: {df_youth[col].nunique(dropna=True)}")
    print(f"Missing: {df_youth[col].isna().sum()}")

    print("\nChoices and frequencies:")

    print(
        df_youth[col]
        .value_counts(dropna=False)
        .to_string()
    )

================================================================================
CHOICES / CLASSES FOR EACH FEATURE
================================================================================

--------------------------------------------------------------------------------
1. youth_id
--------------------------------------------------------------------------------
Data type: object
Number of choices: 83
Missing: 0

Choices and frequencies:
youth_id
Y001    1
Y002    1
Y003    1
Y004    1
Y005    1
Y006    1
Y007    1
Y008    1
Y009    1
Y010    1
Y011    1
Y012    1
Y013    1
Y014    1
Y015    1
Y016    1
Y017    1
Y018    1
Y019    1
Y020    1
Y021    1
Y022    1
Y023    1
Y024    1
Y025    1
Y026    1
Y027    1
Y028    1
Y029    1
Y030    1
Y031    1
Y032    1
Y033    1
Y034    1
Y035    1
Y036    1
Y037    1
Y038    1
Y039    1
Y040    1
Y041    1
Y042    1
Y043    1
Y044    1
Y045    1
Y046    1
Y047    1
Y048    1
Y049    1
Y050    1
Y051    1
Y052    1
Y053    1
Y054    1
Y055    1
Y056    1
Y057    1
Y058    1
Y059    1
Y060    1
Y061    1
Y062    1
Y063    1
Y064    1
Y065    1
Y066    1
Y067    1
Y068    1
Y069    1
Y070    1
Y071    1
Y072    1
Y073    1
Y074    1
Y075    1
Y076    1
Y077    1
Y078    1
Y079    1
Y080    1
Y081    1
Y082    1
Y083    1

--------------------------------------------------------------------------------
2. education_level
--------------------------------------------------------------------------------
Data type: object
Number of choices: 5
Missing: 0

Choices and frequencies:
education_level
Bachelor’s degree                        56
Master’s degree                          12
Technical / vocational education         10
Professional or online certificate(s)     4
Doctorate / PhD                           1

--------------------------------------------------------------------------------
3. field_of_study
--------------------------------------------------------------------------------
Data type: object
Number of choices: 68
Missing: 1

Choices and frequencies:
field_of_study
Computer science                                5
Computer Science                                3
Architecture                                    3
Psychology                                      2
Accounting                                      2
English literature                              2
Business                                        2
Medicine                                        2
Graphic Design                                  2
Graphic design                                  1
Designer                                        1
Dentistry                                       1
BMIS                                            1
Data science                                    1
Psychology/graphic design                       1
Social sciences                                 1
الصف التاسع معلم حلاقه                          1
Computer and communication engineering          1
Cce                                             1
Dental laboratory- lawyer                       1
Management information system                   1
Electrical Engineering                          1
Computer and Communication Engineering          1
Information Technology                          1
Litterature francaise                           1
Nutrition and dietetics                         1
علوم اجتماعية-social science                    1
Business information technology                 1
Translation Studies                             1
Computer Engineering                            1
Business Marketing                              1
Teaching English As a second language           1
interior design                                 1
English                                         1
Biology                                         1
Human Resources Management                      1
الرقابة الصحية وسلامة الغذاء                    1
Biomedical scientist                            1
Technology                                      1
Communication engineering                       1
Biomedical Sciences                             1
Estetich                                        1
Computer engineering                            1
Manage information system                       1
Engineering and Law                             1
Translation and interpretation                  1
Chemistry                                       1
Nursing and English literature                  1
computer science                                1
علوم اجتماعية                                   1
Social worker                                   1
Medical Social worker                           1
هندسة كمبيوتر                                   1
Management Information System                   1
Hospitality and tourism management              1
electro mechanics / renewable energy            1
Business/ finance and financial institutions    1
علم الاجتماع وإدارة الموارد البشرية             1
علوم سياسية وادارية                             1
Ecology - Wildlife Conservation                 1
NaN                                             1
Advertising and marketing communications        1
CCE                                             1
Communication and computer engineering          1
Mis                                             1
Law                                             1
MIS                                             1
Management Information Systems                  1
Statistics                                      1

--------------------------------------------------------------------------------
4. current_status
--------------------------------------------------------------------------------
Data type: object
Number of choices: 5
Missing: 0

Choices and frequencies:
current_status
I am currently unemployed and actively looking for work                                                                    49
I earn income through freelancing, temporary, informal, or occasional work, but I am looking for more stable employment    11
I am currently unemployed but not actively looking for work                                                                 9
I am working, but my current work does not provide the career opportunities, stability, or conditions I am looking for      8
Other                                                                                                                       6

--------------------------------------------------------------------------------
5. job_search_duration
--------------------------------------------------------------------------------
Data type: object
Number of choices: 6
Missing: 0

Choices and frequencies:
job_search_duration
Less than 3 months            19
6–12 months                   16
I am not currently looking    14
More than 1 year              13
3–6 months                    13
More than 2 years              8

--------------------------------------------------------------------------------
6. applications_3m
--------------------------------------------------------------------------------
Data type: object
Number of choices: 4
Missing: 21

Choices and frequencies:
applications_3m
1–5             26
NaN             21
More than 20    17
6–10            12
11–20            7

--------------------------------------------------------------------------------
7. job_opportunity_source
--------------------------------------------------------------------------------
Data type: object
Number of choices: 47
Missing: 0

Choices and frequencies:
job_opportunity_source
Online job platforms / websites                                                                                                                                                                                                                                                                                    9
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media                                                                                                                                                                                                                                  7
I rarely hear about suitable opportunities                                                                                                                                                                                                                                                                         6
Online job platforms / websites\nSocial media                                                                                                                                                                                                                                                                      6
Online job platforms / websites\nSocial media\nFriends or family                                                                                                                                                                                                                                                   4
Friends or family                                                                                                                                                                                                                                                                                                  3
Online job platforms / websites\nLinkedIn or professional platforms                                                                                                                                                                                                                                                3
Social media\nFriends or family\nNGO or community organization                                                                                                                                                                                                                                                     2
LinkedIn or professional platforms                                                                                                                                                                                                                                                                                 2
NGO or community organization                                                                                                                                                                                                                                                                                      2
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family                                                                                                                                                                                                               2
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections                                                                                                                                                                         2
Online job platforms / websites\nSocial media\nFriends or family\nPersonal or professional connections\nUniversity / educational institution                                                                                                                                                                       1
Social media\nPersonal or professional connections                                                                                                                                                                                                                                                                 1
Personal or professional connections                                                                                                                                                                                                                                                                               1
Online job platforms / websites\nLinkedIn or professional platforms\nFriends or family\nI rarely hear about suitable opportunities                                                                                                                                                                                 1
Online job platforms / websites\nFriends or family\nNGO or community organization                                                                                                                                                                                                                                  1
Online job platforms / websites\nLinkedIn or professional platforms\nPersonal or professional connections                                                                                                                                                                                                          1
LinkedIn or professional platforms\nSocial media                                                                                                                                                                                                                                                                   1
LinkedIn or professional platforms\nI rarely hear about suitable opportunities                                                                                                                                                                                                                                     1
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nUniversity / educational institution\nNGO or community organization                                                                                                                                                             1
Friends or family\nI rarely hear about suitable opportunities                                                                                                                                                                                                                                                      1
Online job platforms / websites\nPersonal or professional connections\nDirectly from employers                                                                                                                                                                                                                     1
Online job platforms / websites\nFriends or family                                                                                                                                                                                                                                                                 1
Online job platforms / websites\nFriends or family\nRecruitment agency\nDirectly from employers\nI rarely hear about suitable opportunities                                                                                                                                                                        1
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nRecruitment agency\nDirectly from employers                                                                                                                                                                  1
Online job platforms / websites\nPersonal or professional connections\nNGO or community organization                                                                                                                                                                                                               1
LinkedIn or professional platforms\nFriends or family                                                                                                                                                                                                                                                              1
LinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections\nDirectly from employers                                                                                                                                                                                 1
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections\nUniversity / educational institution\nNGO or community organization                                                                                                    1
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections\nUniversity / educational institution\nNGO or community organization\nRecruitment agency\nDirectly from employers\nI rarely hear about suitable opportunities\nOther    1
LinkedIn or professional platforms\nSocial media\nFriends or family\nNGO or community organization                                                                                                                                                                                                                 1
Social media                                                                                                                                                                                                                                                                                                       1
University / educational institution                                                                                                                                                                                                                                                                               1
Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections\nUniversity / educational institution                                                                                                                                   1
Friends or family\nPersonal or professional connections\nNGO or community organization                                                                                                                                                                                                                             1
LinkedIn or professional platforms\nSocial media\nFriends or family\nDirectly from employers                                                                                                                                                                                                                       1
LinkedIn or professional platforms\nNGO or community organization                                                                                                                                                                                                                                                  1
Online job platforms / websites\nLinkedIn or professional platforms\nFriends or family\nNGO or community organization                                                                                                                                                                                              1
Online job platforms / websites\nFriends or family\nRecruitment agency\nI rarely hear about suitable opportunities                                                                                                                                                                                                 1

In [13]:
df_youth["applications_3m"] = df_youth["applications_3m"].fillna("None")

In [14]:
# ============================================================
# SET DATA TYPES
# ============================================================

# 1. Youth ID as string / identifier
df_youth["youth_id"] = df_youth["youth_id"].astype("string")


# 2. All survey questions except the last one as categorical
categorical_cols = [
    "education_level",
    "field_of_study",
    "current_status",
    "job_search_barriers",
    "job_search_duration",
    "applications_3m",
    "job_opportunity_source",
    "biggest_difficulty",
    "difficult_job_search_stage",
    "application_outcome",
    "experience_requirement",
    "importance_connections",
    "needed_connection",
    "education_job_preparation",
    "missing_skills",
    "entry_level_experience",
    "interview_without_offer",
    "interview_difficulties",
    "rejection_effect",
    "employer_feedback",
    "security_impact",
    "job_acceptance_barriers",
    "low_salary_response",
    "modern_work_access",
    "work_abroad_preference",
    "reasons_work_abroad",
    "employment_support",
    "most_valuable_service"
]

# Convert to categorical
for col in categorical_cols:
    df_youth[col] = df_youth[col].astype("category")


# 3. Last question = open-ended text
df_youth["needed_systemic_change"] = (
    df_youth["needed_systemic_change"].astype("string")
)


# ============================================================
# CHECK TYPES
# ============================================================

print("=" * 80)
print("DATA TYPES")
print("=" * 80)

display(
    pd.DataFrame({
        "Feature": df_youth.columns,
        "Data Type": df_youth.dtypes.astype(str).values
    })
)

================================================================================
DATA TYPES
================================================================================

                       Feature Data Type
0                     youth_id    string
1              education_level  category
2               field_of_study  category
3               current_status  category
4          job_search_duration  category
5              applications_3m  category
6       job_opportunity_source  category
7          job_search_barriers  category
8           biggest_difficulty  category
9   difficult_job_search_stage  category
10         application_outcome  category
11      experience_requirement  category
12      importance_connections  category
13           needed_connection  category
14   education_job_preparation  category
15              missing_skills  category
16      entry_level_experience  category
17     interview_without_offer  category
18      interview_difficulties  category
19            rejection_effect  category
20           employer_feedback  category
21             security_impact  category
22     job_acceptance_barriers  category
23         low_salary_response  category
24          modern_work_access  category
25      work_abroad_preference  category
26         reasons_work_abroad  category
27          employment_support  category
28       most_valuable_service  category
29      needed_systemic_change    string

In [15]:
# ============================================================
# 5. GENERAL COLUMN SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("COLUMN SUMMARY")
print("=" * 80)

summary = pd.DataFrame({
    "Feature": df_youth.columns,
    "Data Type": df_youth.dtypes.astype(str).values,
    "Missing": df_youth.isna().sum().values,
    "Missing %": (df_youth.isna().mean() * 100).round(2).values,
    "Number of Choices": df_youth.nunique(dropna=True).values
})

display(summary)

================================================================================
COLUMN SUMMARY
================================================================================

,Feature,Data Type,Missing,Missing %,Number of Choices
0,youth_id,string,0,0.00,83
1,education_level,category,0,0.00,5
2,field_of_study,category,1,1.20,68
3,current_status,category,0,0.00,5
4,job_search_duration,category,0,0.00,6
5,applications_3m,category,0,0.00,5
6,job_opportunity_source,category,0,0.00,47
7,job_search_barriers,category,0,0.00,59
8,biggest_difficulty,category,0,0.00,10
9,difficult_job_search_stage,category,0,0.00,9
10,application_outcome,category,0,0.00,6
11,experience_requirement,category,0,0.00,6
12,importance_connections,category,0,0.00,6
13,needed_connection,category,0,0.00,5
14,education_job_preparation,category,0,0.00,6
15,missing_skills,category,0,0.00,45
16,entry_level_experience,category,0,0.00,6
17,interview_without_offer,category,0,0.00,6
18,interview_difficulties,category,0,0.00,38
19,rejection_effect,category,0,0.00,5
20,employer_feedback,category,0,0.00,5
21,security_impact,category,0,0.00,5
22,job_acceptance_barriers,category,0,0.00,62
23,low_salary_response,category,0,0.00,8
24,modern_work_access,category,0,0.00,7
25,work_abroad_preference,category,0,0.00,6
26,reasons_work_abroad,category,0,0.00,55
27,employment_support,category,0,0.00,59
28,most_valuable_service,category,0,0.00,11
29,needed_systemic_change,string,22,26.51,59

In [15]:
# ============================================================
#  DUPLICATES
# ============================================================

print("\n" + "=" * 80)
print("DUPLICATES")
print("=" * 80)

print("Duplicate rows:", df_youth.duplicated().sum())

================================================================================
DUPLICATES
================================================================================
Duplicate rows: 0

In [16]:
# ============================================================
#  UNIQUE CHOICE SUMMARY
# ============================================================

print("\n" + "=" * 80)
print("NUMBER OF CHOICES PER FEATURE")
print("=" * 80)

choice_summary = pd.DataFrame({
    "Feature": df_youth.columns,
    "Number of Choices": [
        df_youth[col].nunique(dropna=True)
        for col in df_youth.columns
    ]
})

display(choice_summary)

================================================================================
NUMBER OF CHOICES PER FEATURE
================================================================================

                       Feature  Number of Choices
0                     youth_id                 83
1              education_level                  5
2               field_of_study                 68
3               current_status                  5
4          job_search_duration                  6
5              applications_3m                  5
6       job_opportunity_source                 47
7          job_search_barriers                 59
8           biggest_difficulty                 10
9   difficult_job_search_stage                  9
10         application_outcome                  6
11      experience_requirement                  6
12      importance_connections                  6
13           needed_connection                  5
14   education_job_preparation                  6
15              missing_skills                 45
16      entry_level_experience                  6
17     interview_without_offer                  6
18      interview_difficulties                 38
19            rejection_effect                  5
20           employer_feedback                  5
21             security_impact                  5
22     job_acceptance_barriers                 62
23         low_salary_response                  8
24          modern_work_access                  7
25      work_abroad_preference                  6
26         reasons_work_abroad                 55
27          employment_support                 59
28       most_valuable_service                 11
29      needed_systemic_change                 59

In [1]:
output_path = r"c:\Users\User\Desktop\youth unemployement\youth_data_edited.xlsx"

df_youth.to_excel(output_path, index=False)

print(f"Saved to: {output_path}")

NameError: name 'df_youth' is not defined

In [2]:
#clean up

import pandas as pd
import numpy as np

file_path = r"C:\Users\User\Desktop\youth unemployement\youth_data_edited.xlsx"  # Change to your actual file

# Excel
df_youth = pd.read_excel(file_path)

In [3]:
for i, col in enumerate(df_youth.columns, 1):
    print(f"{i}. {col}")

1. youth_id
2. education_level
3. field_of_study
4. current_status
5. job_search_duration
6. applications_3m
7. job_opportunity_source
8. job_search_barriers
9. biggest_difficulty
10. difficult_job_search_stage
11. application_outcome
12. experience_requirement
13. importance_connections
14. needed_connection
15. education_job_preparation
16. missing_skills
17. entry_level_experience
18. interview_without_offer
19. interview_difficulties
20. rejection_effect
21. employer_feedback
22. security_impact
23. job_acceptance_barriers
24. low_salary_response
25. modern_work_access
26. work_abroad_preference
27. reasons_work_abroad
28. employment_support
29. most_valuable_service
30. needed_systemic_change

In [4]:
feature_order = pd.DataFrame({
    "Order": range(1, len(df_youth.columns) + 1),
    "Feature": df_youth.columns
})

display(feature_order)

    Order                     Feature
0       1                    youth_id
1       2             education_level
2       3              field_of_study
3       4              current_status
4       5         job_search_duration
5       6             applications_3m
6       7      job_opportunity_source
7       8         job_search_barriers
8       9          biggest_difficulty
9      10  difficult_job_search_stage
10     11         application_outcome
11     12      experience_requirement
12     13      importance_connections
13     14           needed_connection
14     15   education_job_preparation
15     16              missing_skills
16     17      entry_level_experience
17     18     interview_without_offer
18     19      interview_difficulties
19     20            rejection_effect
20     21           employer_feedback
21     22             security_impact
22     23     job_acceptance_barriers
23     24         low_salary_response
24     25          modern_work_access
25     26      work_abroad_preference
26     27         reasons_work_abroad
27     28          employment_support
28     29       most_valuable_service
29     30      needed_systemic_change

In [5]:
multi_choice_cols = [
    "job_opportunity_source",
    "job_search_barriers",
    "missing_skills",
    "interview_difficulties",
    "job_acceptance_barriers",
    "reasons_work_abroad",
    "employment_support"
]

for col in multi_choice_cols:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)

    print(df_youth[col].dropna().head(10).to_string(index=False))

    print("\nUnique response formats:")
    for value in df_youth[col].dropna().unique()[:10]:
        print(repr(value))

================================================================================
job_opportunity_source
================================================================================
              Personal or professional connections
Online job platforms / websites\nLinkedIn or pr...
Online job platforms / websites\nSocial media\n...
                   Online job platforms / websites
                LinkedIn or professional platforms
        I rarely hear about suitable opportunities
Social media\nPersonal or professional connections
Online job platforms / websites\nLinkedIn or pr...
LinkedIn or professional platforms\nI rarely he...
        I rarely hear about suitable opportunities

Unique response formats:
'Personal or professional connections'
'Online job platforms / websites\nLinkedIn or professional platforms\nSocial media'
'Online job platforms / websites\nSocial media\nFriends or family\nPersonal or professional connections\nUniversity / educational institution'
'Online job platforms / websites'
'LinkedIn or professional platforms'
'I rarely hear about suitable opportunities'
'Social media\nPersonal or professional connections'
'Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nFriends or family\nPersonal or professional connections'
'LinkedIn or professional platforms\nI rarely hear about suitable opportunities'
'Online job platforms / websites\nLinkedIn or professional platforms\nSocial media\nUniversity / educational institution\nNGO or community organization'

================================================================================
job_search_barriers
================================================================================
High competition for available positions\nLack ...
High competition for available positions\nLack ...
          High competition for available positions
Location of available jobs / distance from wher...
High competition for available positions\nLack ...
High competition for available positions\nLack ...
Limited job opportunities in my field\nLack of ...
Lack of practical work experience\nDiscriminati...
High competition for available positions\nLack ...
  Discrimination or bias during the hiring process

Unique response formats:
'High competition for available positions\nLack of professional connections or networking opportunities\nLocation of available jobs / distance from where I live\nTransportation or commuting difficulties\nSalary levels offered by employers'
'High competition for available positions\nLack of practical work experience'
'High competition for available positions'
'Location of available jobs / distance from where I live'
'High competition for available positions\nLack of practical work experience\nLack of technical or digital skills required by employers\nLack of soft skills required by employers (e.g., communication, teamwork, adaptability)\nLack of professional connections or networking opportunities\nDiscrimination or bias during the hiring process\nStress, discouragement, or loss of motivation during the job search'
'Limited job opportunities in my field\nLack of professional connections or networking opportunities\nLocation of available jobs / distance from where I live'
'Lack of practical work experience\nDiscrimination or bias during the hiring process\nLocation of available jobs / distance from where I live\nTransportation or commuting difficulties\nSalary levels offered by employers\nStress, discouragement, or loss of motivation during the job search'
'High competition for available positions\nLack of practical work experience\nLack of professional connections or networking opportunities\nSalary levels offered by employers'
'Discrimination or bias during the hiring process'
'Limited job opportunities in my field\nDiscrimination or bias during the hiring process'

================================================================================
missing_skills
================================================================================
 Communication skills\nPractical / work experience
Technical / job-specific skills\nPractical / wo...
                                             Other
                                             Other
Technical / job-specific skills\nEnglish or oth...
                          I do not feel unprepared
    Communication skills\nI do not feel unprepared
                       Practical / work experience
Interview skills\nPractical / work experience\n...
Technical / job-specific skills\nDigital skills...

Unique response formats:
'Communication skills\nPractical / work experience'
'Technical / job-specific skills\nPractical / work experience'
'Other'
'Technical / job-specific skills\nEnglish or other language skills\nCommunication skills\nPractical / work experience'
'I do not feel unprepared'
'Communication skills\nI do not feel unprepared'
'Practical / work experience'
'Interview skills\nPractical / work experience\nKnowledge of the Lebanese job market'
'Technical / job-specific skills\nDigital skills\nCommunication skills'
'Technical / job-specific skills\nDigital skills'

================================================================================
interview_difficulties
================================================================================
Answering technical/job-specific questions\nCom...
Answering technical/job-specific questions\nUnd...
                  I have not attended an interview
               Understanding what employers expect
Answering technical/job-specific questions\nCom...
                  I have not attended an interview
Explaining my skills and experience\nCommunicat...
Explaining my skills and experience\nAnswering ...
Communicating confidently\nUnderstanding what e...
Communicating confidently\nManaging stress or n...

Unique response formats:
'Answering technical/job-specific questions\nCommunicating confidently'
'Answering technical/job-specific questions\nUnderstanding what employers expect\nI generally feel comfortable in interviews'
'I have not attended an interview'
'Understanding what employers expect'
'Answering technical/job-specific questions\nCommunicating confidently\nUnderstanding what employers expect'
'Explaining my skills and experience\nCommunicating confidently'
'Explaining my skills and experience\nAnswering technical/job-specific questions\nCommunicating confidently\nUnderstanding what employers expect\nManaging stress or nervousness'
'Communicating confidently\nUnderstanding what employers expect'
'Communicating confidently\nManaging stress or nervousness'
'Explaining my skills and experience\nAnswering technical/job-specific questions\nAnswering behavioral or personal questions\nCommunicating confidently'

================================================================================
job_acceptance_barriers
================================================================================
Low salary\nSalary does not cover basic living ...
        Lack of training or learning opportunities
                                  Lack of benefits
Low salary\nSalary does not cover basic living ...
Salary does not cover basic living costs\nPoor ...
                                        Low salary
Salary does not cover basic living costs\nLack ...
Low salary\nSalary does not cover basic living ...
Low salary\nLong working hours\nJob responsibil...
Low salary\nSalary does not cover basic living ...

Unique response formats:
'Low salary\nSalary does not cover basic living costs\nLong working hours\nLack of remote / hybrid options'
'Lack of training or learning opportunities'
'Lack of benefits'
'Low salary\nSalary does not cover basic living costs\nLong working hours\nLong commuting distance'
'Salary does not cover basic living costs\nPoor working conditions\nLack of training or learning opportunities\nJob responsibilities do not match my qualifications or career goals'
'Low salary'
'Salary does not cover basic living costs\nLack of job security\nLack of training or learning opportunities\nJob responsibilities do not match my qualifications or career goals'
'Low salary\nSalary does not cover basic living costs\nLack of job security\nPoor working conditions\nLong commuting distance\nLack of remote / hybrid options\nJob responsibilities do not match my qualifications or career goals'
'Low salary\nLong working hours\nJob responsibilities do not match my qualifications or career goals'
'Low salary\nSalary does not cover basic living costs\nLack of training or learning opportunities'

================================================================================
reasons_work_abroad
================================================================================
Higher salary\nBetter career opportunities\nBet...
Higher salary\nBetter career opportunities\nEco...
        Higher salary\nBetter career opportunities
Higher salary\nLack of suitable opportunities i...
Higher salary\nBetter career opportunities\nMor...
         Lack of suitable opportunities in Lebanon
               I would prefer to remain in Lebanon
               I would prefer to remain in Lebanon
Higher salary\nBetter career opportunities\nBet...
Higher salary\nBetter career opportunities\nGre...

Unique response formats:
'Higher salary\nBetter career opportunities\nBetter working conditions\nLack of suitable opportunities in Lebanon\nEconomic conditions in Lebanon'
'Higher salary\nBetter career opportunities\nEconomic conditions in Lebanon\nProfessional development\nI would prefer to remain in Lebanon'
'Higher salary\nBetter career opportunities'
'Higher salary\nLack of suitable opportunities in Lebanon'
'Higher salary\nBetter career opportunities\nMore opportunities related to my field\nLack of suitable opportunities in Lebanon\nProfessional development'
'Lack of suitable opportunities in Lebanon'
'I would prefer to remain in Lebanon'
'Higher salary\nBetter career opportunities\nBetter working conditions\nMore opportunities related to my field\nLack of suitable opportunities in Lebanon\nEconomic conditions in Lebanon\nSecurity / stability\nProfessional development'
'Higher salary\nBetter career opportunities\nGreater job stability\nBetter working conditions\nMore opportunities related to my field\nLack of suitable opportunities in Lebanon\nEconomic conditions in Lebanon\nSecurity / stability\nProfessional development'
'Higher salary\nBetter career opportunities\nGreater job stability\nBetter working conditions\nMore opportunities related to my field\nLack of suitable opportunities in Lebanon\nEconomic conditions in Lebanon\nSecurity / stability\nProfessional development\nOther'

================================================================================
employment_support
================================================================================
Paid internship / practical work experience\nTe...
Paid internship / practical work experience\nTe...
Paid internship / practical work experience\nDi...
       Paid internship / practical work experience
Technical / job-specific skills training\nSoft-...
            Financial support during job searching
Paid internship / practical work experience\nSo...
Paid internship / practical work experience\nTr...
Paid internship / practical work experience\nJo...
Paid internship / practical work experience\nTe...

Unique response formats:
'Paid internship / practical work experience\nTechnical / job-specific skills training\nCareer guidance'
'Paid internship / practical work experience\nTechnical / job-specific skills training\nInterview preparation'
'Paid internship / practical work experience\nDigital skills training\nProfessional certifications'
'Paid internship / practical work experience'
'Technical / job-specific skills training\nSoft-skills training\nNetworking opportunities with employers'
'Financial support during job searching'
'Paid internship / practical work experience\nSoft-skills training\nMentorship from professionals'
'Paid internship / practical work experience\nTransportation support'
'Paid internship / practical work experience\nJob-matching services\nNetworking opportunities with employers'
'Paid internship / practical work experience\nTechnical / job-specific skills training\nNetworking opportunities with employers'

In [6]:
# ============================================================
# LOWERCASE ALL CATEGORICAL FEATURE VALUES
# ============================================================

# Columns that should NOT be lowercased
exclude_cols = [
    "youth_id",
    "needed_systemic_change"
]

# All other columns
categorical_cols = [
    col for col in df_youth.columns
    if col not in exclude_cols
]

# Convert values to lowercase
for col in categorical_cols:
    if df_youth[col].dtype == "object":
        df_youth[col] = df_youth[col].apply(
            lambda x: x.lower().strip() if isinstance(x, str) else x
        )

# ============================================================
# CHECK
# ============================================================

print("Categorical columns converted to lowercase:")

for col in categorical_cols:
    print(f"- {col}")

Categorical columns converted to lowercase:
- education_level
- field_of_study
- current_status
- job_search_duration
- applications_3m
- job_opportunity_source
- job_search_barriers
- biggest_difficulty
- difficult_job_search_stage
- application_outcome
- experience_requirement
- importance_connections
- needed_connection
- education_job_preparation
- missing_skills
- entry_level_experience
- interview_without_offer
- interview_difficulties
- rejection_effect
- employer_feedback
- security_impact
- job_acceptance_barriers
- low_salary_response
- modern_work_access
- work_abroad_preference
- reasons_work_abroad
- employment_support
- most_valuable_service

In [7]:
for col in [
    "education_level",
    "current_status",
    "job_search_barriers",
    "missing_skills",
    "reasons_work_abroad"
]:
    print("\n" + "=" * 70)
    print(col)
    print("=" * 70)
    print(df_youth[col].dropna().head(5).to_string(index=False))

======================================================================
education_level
======================================================================
bachelor’s degree
bachelor’s degree
bachelor’s degree
bachelor’s degree
  doctorate / phd

======================================================================
current_status
======================================================================
i am currently unemployed and actively looking ...
i am working, but my current work does not prov...
                                             other
i am currently unemployed and actively looking ...
i am currently unemployed and actively looking ...

======================================================================
job_search_barriers
======================================================================
high competition for available positions\nlack ...
high competition for available positions\nlack ...
          high competition for available positions
location of available jobs / distance from wher...
high competition for available positions\nlack ...

======================================================================
missing_skills
======================================================================
 communication skills\npractical / work experience
technical / job-specific skills\npractical / wo...
                                             other
                                             other
technical / job-specific skills\nenglish or oth...

======================================================================
reasons_work_abroad
======================================================================
higher salary\nbetter career opportunities\nbet...
higher salary\nbetter career opportunities\neco...
        higher salary\nbetter career opportunities
higher salary\nlack of suitable opportunities i...
higher salary\nbetter career opportunities\nmor...

In [9]:
import re
import pandas as pd

# ============================================================
# MULTI-CHOICE QUESTIONS
# ============================================================
#these dummy variables are created for multi-choice questions where respondents can select multiple options. Each unique choice will be represented as a separate binary (0/1) column.

multi_choice_cols = [
    "job_opportunity_source",
    "job_search_barriers",
    "missing_skills",
    "interview_difficulties",
    "job_acceptance_barriers",
    "reasons_work_abroad",
    "employment_support"
]


# ============================================================
# SPECIAL RESPONSES TO EXCLUDE FROM REGULAR DUMMIES
# ============================================================

exclude_choices = {
    "job_opportunity_source": [
        "none of the above",
        "i rarely hear about suitable opportunities"
    ],

    "job_search_barriers": [
        "none of the above"
    ],

    "missing_skills": [
        "none of the above",
        "i do not feel unprepared"
    ],

    "interview_difficulties": [
        "none of the above",
        "i have not attended an interview",
        "i generally feel comfortable in interviews"
    ],

    "job_acceptance_barriers": [
        "none of the above"
    ],

    "reasons_work_abroad": [
        "none of the above",
        "i would prefer to remain in lebanon"
    ],

    "employment_support": [
        "none of the above"
    ]
}


# ============================================================
# CREATE DUMMY VARIABLES
# ============================================================

created_dummies = {}

for col in multi_choice_cols:

    # Get all individual choices
    choices = set()

    for response in df_youth[col].dropna():

        for choice in str(response).split("\n"):

            choice = choice.strip().lower()

            if choice:
                choices.add(choice)

    # Remove special responses
    choices = [
        choice
        for choice in choices
        if choice not in exclude_choices.get(col, [])
    ]

    question_dummies = []

    # Create 0/1 dummy for each genuine choice
    for choice in sorted(choices):

        # Create clean variable name
        clean_choice = re.sub(
            r"[^a-zA-Z0-9]+",
            "_",
            choice
        ).strip("_").lower()

        dummy_name = f"{col}__{clean_choice}"

        df_youth[dummy_name] = (
            df_youth[col]
            .fillna("")
            .astype(str)
            .apply(
                lambda x: int(
                    choice in [
                        c.strip().lower()
                        for c in x.split("\n")
                    ]
                )
            )
            .astype("int8")
        )

        question_dummies.append(dummy_name)

    created_dummies[col] = question_dummies


# ============================================================
# DISPLAY CREATED DUMMIES
# ============================================================

print("=" * 80)
print("DUMMY VARIABLES CREATED")
print("=" * 80)

for question, dummies in created_dummies.items():

    print(f"\n{question}: {len(dummies)} dummy variables")

    for dummy in dummies:
        print(f"   {dummy}")

================================================================================
DUMMY VARIABLES CREATED
================================================================================

job_opportunity_source: 10 dummy variables
   job_opportunity_source__directly_from_employers
   job_opportunity_source__friends_or_family
   job_opportunity_source__linkedin_or_professional_platforms
   job_opportunity_source__ngo_or_community_organization
   job_opportunity_source__online_job_platforms_websites
   job_opportunity_source__other
   job_opportunity_source__personal_or_professional_connections
   job_opportunity_source__recruitment_agency
   job_opportunity_source__social_media
   job_opportunity_source__university_educational_institution

job_search_barriers: 11 dummy variables
   job_search_barriers__discrimination_or_bias_during_the_hiring_process
   job_search_barriers__high_competition_for_available_positions
   job_search_barriers__lack_of_practical_work_experience
   job_search_barriers__lack_of_professional_connections_or_networking_opportunities
   job_search_barriers__lack_of_soft_skills_required_by_employers_e_g_communication_teamwork_adaptability
   job_search_barriers__lack_of_technical_or_digital_skills_required_by_employers
   job_search_barriers__limited_job_opportunities_in_my_field
   job_search_barriers__location_of_available_jobs_distance_from_where_i_live
   job_search_barriers__salary_levels_offered_by_employers
   job_search_barriers__stress_discouragement_or_loss_of_motivation_during_the_job_search
   job_search_barriers__transportation_or_commuting_difficulties

missing_skills: 10 dummy variables
   missing_skills__communication_skills
   missing_skills__digital_skills
   missing_skills__english_or_other_language_skills
   missing_skills__interview_skills
   missing_skills__knowledge_of_the_lebanese_job_market
   missing_skills__other
   missing_skills__practical_work_experience
   missing_skills__problem_solving_critical_thinking
   missing_skills__professional_certifications
   missing_skills__technical_job_specific_skills

interview_difficulties: 8 dummy variables
   interview_difficulties__answering_behavioral_or_personal_questions
   interview_difficulties__answering_technical_job_specific_questions
   interview_difficulties__communicating_confidently
   interview_difficulties__explaining_my_skills_and_experience
   interview_difficulties__interviews_in_english_or_another_language
   interview_difficulties__managing_stress_or_nervousness
   interview_difficulties__online_interview_technology
   interview_difficulties__understanding_what_employers_expect

job_acceptance_barriers: 12 dummy variables
   job_acceptance_barriers__job_responsibilities_do_not_match_my_qualifications_or_career_goals
   job_acceptance_barriers__lack_of_benefits
   job_acceptance_barriers__lack_of_career_progression
   job_acceptance_barriers__lack_of_job_security
   job_acceptance_barriers__lack_of_remote_hybrid_options
   job_acceptance_barriers__lack_of_training_or_learning_opportunities
   job_acceptance_barriers__long_commuting_distance
   job_acceptance_barriers__long_working_hours
   job_acceptance_barriers__low_salary
   job_acceptance_barriers__other
   job_acceptance_barriers__poor_working_conditions
   job_acceptance_barriers__salary_does_not_cover_basic_living_costs

reasons_work_abroad: 11 dummy variables
   reasons_work_abroad__better_career_opportunities
   reasons_work_abroad__better_working_conditions
   reasons_work_abroad__economic_conditions_in_lebanon
   reasons_work_abroad__greater_job_stability
   reasons_work_abroad__higher_salary
   reasons_work_abroad__lack_of_suitable_opportunities_in_lebanon
   reasons_work_abroad__more_opportunities_related_to_my_field
   reasons_work_abroad__other
   reasons_work_abroad__professional_development
   reasons_work_abroad__security_stability
   reasons_work_abroad__

employment_support: 16 dummy variables
   employment_support__apprenticeships_workplace_training
   employment_support__career_guidance
   employment_support__cv_application_support
   employment_support__digital_skills_training
   employment_support__english_language_training
   employment_support__entrepreneurship_support
   employment_support__financial_support_during_job_searching
   employment_support__interview_preparation
   employment_support__job_matching_services
   employment_support__mentorship_from_professionals
   employment_support__networking_opportunities_with_employers
   employment_support__paid_internship_practical_work_experience
   employment_support__professional_certifications
   employment_support__soft_skills_training
   employment_support__technical_job_specific_skills_training
   employment_support__transportation_support

In [10]:
#start of descriptive analysis

In [11]:
# ============================================================
# FREQUENCY OF EACH MULTI-CHOICE OPTION
# ============================================================

for question, dummies in created_dummies.items():

    print("\n" + "=" * 80)
    print(question)
    print("=" * 80)

    results = pd.DataFrame({
        "count": df_youth[dummies].sum(),
        "percentage": (
            df_youth[dummies].mean() * 100
        ).round(1)
    })

    results = results.sort_values(
        "count",
        ascending=False
    )

    # Make the option names easier to read
    results.index = [
        x.replace(question + "__", "").replace("_", " ")
        for x in results.index
    ]

    display(results)

================================================================================
job_opportunity_source
================================================================================

                                      count  percentage
online job platforms websites            54        65.1
social media                             39        47.0
linkedin or professional platforms       36        43.4
friends or family                        35        42.2
personal or professional connections     14        16.9
ngo or community organization            14        16.9
directly from employers                   7         8.4
university educational institution        7         8.4
recruitment agency                        5         6.0
other                                     1         1.2

================================================================================
job_search_barriers
================================================================================

                                                    count  percentage
lack of practical work experience                      36        43.4
location of available jobs distance from where ...     35        42.2
high competition for available positions               32        38.6
limited job opportunities in my field                  28        33.7
transportation or commuting difficulties               21        25.3
salary levels offered by employers                     19        22.9
lack of professional connections or networking ...     18        21.7
discrimination or bias during the hiring process       17        20.5
stress discouragement or loss of motivation dur...     10        12.0
lack of technical or digital skills required by...      9        10.8
lack of soft skills required by employers e g c...      4         4.8

================================================================================
missing_skills
================================================================================

                                      count  percentage
practical work experience                32        38.6
technical job specific skills            31        37.3
interview skills                         21        25.3
english or other language skills         19        22.9
communication skills                     16        19.3
knowledge of the lebanese job market     12        14.5
professional certifications               9        10.8
digital skills                            8         9.6
problem solving critical thinking         6         7.2
other                                     5         6.0

================================================================================
interview_difficulties
================================================================================

                                            count  percentage
answering technical job specific questions     19        22.9
communicating confidently                      17        20.5
understanding what employers expect            17        20.5
managing stress or nervousness                 16        19.3
interviews in english or another language      14        16.9
explaining my skills and experience            14        16.9
answering behavioral or personal questions      6         7.2
online interview technology                     3         3.6

================================================================================
job_acceptance_barriers
================================================================================

                                                    count  percentage
low salary                                             44        53.0
salary does not cover basic living costs               42        50.6
lack of training or learning opportunities             25        30.1
long working hours                                     24        28.9
poor working conditions                                18        21.7
lack of remote hybrid options                          17        20.5
lack of benefits                                       16        19.3
job responsibilities do not match my qualificat...     15        18.1
long commuting distance                                15        18.1
lack of career progression                             14        16.9
lack of job security                                   11        13.3
other                                                   4         4.8

================================================================================
reasons_work_abroad
================================================================================

                                           count  percentage
higher salary                                 64        77.1
better career opportunities                   56        67.5
economic conditions in lebanon                46        55.4
better working conditions                     42        50.6
greater job stability                         38        45.8
more opportunities related to my field        37        44.6
security stability                            36        43.4
lack of suitable opportunities in lebanon     33        39.8
professional development                      33        39.8
other                                          3         3.6
                                               1         1.2

================================================================================
employment_support
================================================================================

                                           count  percentage
paid internship practical work experience     54        65.1
technical job specific skills training        23        27.7
networking opportunities with employers       17        20.5
cv application support                        14        16.9
interview preparation                         14        16.9
english language training                     14        16.9
transportation support                        13        15.7
digital skills training                       13        15.7
mentorship from professionals                  9        10.8
career guidance                                8         9.6
apprenticeships workplace training             7         8.4
financial support during job searching         6         7.2
professional certifications                    6         7.2
soft skills training                           6         7.2
job matching services                          4         4.8
entrepreneurship support                       3         3.6

In [12]:

#Sample profile

def categorical_summary(df, col):
    summary = (
        df[col]
        .value_counts(dropna=False)
        .rename_axis("category")
        .reset_index(name="frequency")
    )

    summary["percentage"] = (
        summary["frequency"] / len(df) * 100
    ).round(1)

    return summary


profile_vars = [
    "education_level",
    "field_of_study",
    "current_status"
]

for col in profile_vars:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)
    display(categorical_summary(df_youth, col))

================================================================================
education_level
================================================================================

                                category  frequency  percentage
0                      bachelor’s degree         56        67.5
1                        master’s degree         12        14.5
2       technical / vocational education         10        12.0
3  professional or online certificate(s)          4         4.8
4                        doctorate / phd          1         1.2

================================================================================
field_of_study
================================================================================

                                  category  frequency  percentage
0                         computer science          9        10.8
1                           graphic design          3         3.6
2                             architecture          3         3.6
3                                      cce          2         2.4
4            management information system          2         2.4
..                                     ...        ...         ...
56                                     NaN          1         1.2
57  communication and computer engineering          1         1.2
58                                     law          1         1.2
59          management information systems          1         1.2
60                              statistics          1         1.2

[61 rows x 3 columns]

================================================================================
current_status
================================================================================

                                            category  frequency  percentage
0  i am currently unemployed and actively looking...         49        59.0
1  i earn income through freelancing, temporary, ...         11        13.3
2  i am currently unemployed but not actively loo...          9        10.8
3  i am working, but my current work does not pro...          8         9.6
4                                              other          6         7.2

In [13]:
#Job-search situation

job_search_vars = [
    "job_search_duration",
    "applications_3m",
    "job_opportunity_source",
    "biggest_difficulty",
    "difficult_job_search_stage",
    "application_outcome",
    "experience_requirement",
    "entry_level_experience",
    "interview_without_offer",
    "employer_feedback"
]

for col in job_search_vars:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)

    display(categorical_summary(df_youth, col))

================================================================================
job_search_duration
================================================================================

                     category  frequency  percentage
0          less than 3 months         19        22.9
1                 6–12 months         16        19.3
2  i am not currently looking         14        16.9
3            more than 1 year         13        15.7
4                  3–6 months         13        15.7
5           more than 2 years          8         9.6

================================================================================
applications_3m
================================================================================

       category  frequency  percentage
0           1–5         26        31.3
1           NaN         21        25.3
2  more than 20         17        20.5
3          6–10         12        14.5
4         11–20          7         8.4

================================================================================
job_opportunity_source
================================================================================

                                             category  frequency  percentage
0                     online job platforms / websites          9        10.8
1   online job platforms / websites\nlinkedin or p...          7         8.4
2          i rarely hear about suitable opportunities          6         7.2
3       online job platforms / websites\nsocial media          6         7.2
4   online job platforms / websites\nsocial media\...          4         4.8
5                                   friends or family          3         3.6
6   online job platforms / websites\nlinkedin or p...          3         3.6
7   social media\nfriends or family\nngo or commun...          2         2.4
8                  linkedin or professional platforms          2         2.4
9                       ngo or community organization          2         2.4
10  online job platforms / websites\nlinkedin or p...          2         2.4
11  online job platforms / websites\nlinkedin or p...          2         2.4
12  online job platforms / websites\nsocial media\...          1         1.2
13  social media\npersonal or professional connect...          1         1.2
14               personal or professional connections          1         1.2
15  online job platforms / websites\nlinkedin or p...          1         1.2
16  online job platforms / websites\nfriends or fa...          1         1.2
17  online job platforms / websites\nlinkedin or p...          1         1.2
18   linkedin or professional platforms\nsocial media          1         1.2
19  linkedin or professional platforms\ni rarely h...          1         1.2
20  online job platforms / websites\nlinkedin or p...          1         1.2
21  friends or family\ni rarely hear about suitabl...          1         1.2
22  online job platforms / websites\npersonal or p...          1         1.2
23  online job platforms / websites\nfriends or fa...          1         1.2
24  online job platforms / websites\nfriends or fa...          1         1.2
25  online job platforms / websites\nlinkedin or p...          1         1.2
26  online job platforms / websites\npersonal or p...          1         1.2
27  linkedin or professional platforms\nfriends or...          1         1.2
28  linkedin or professional platforms\nsocial med...          1         1.2
29  online job platforms / websites\nlinkedin or p...          1         1.2
30  online job platforms / websites\nlinkedin or p...          1         1.2
31  linkedin or professional platforms\nsocial med...          1         1.2
32                                       social media          1         1.2
33               university / educational institution          1         1.2
34  online job platforms / websites\nlinkedin or p...          1         1.2
35  friends or family\npersonal or professional co...          1         1.2
36  linkedin or professional platforms\nsocial med...          1         1.2
37  linkedin or professional platforms\nngo or com...          1         1.2
38  online job platforms / websites\nlinkedin or p...          1         1.2
39  online job platforms / websites\nfriends or fa...          1         1.2
40  linkedin or professional platforms\nsocial med...          1         1.2
41  online job platforms / websites\nlinkedin or p...          1         1.2
42  online job platforms / websites\nlinkedin or p...          1         1.2
43  online job platforms / websites\nfriends or fa...          1         1.2
44  online job platforms / websites\nlinkedin or p...          1         1.2
45  online job platforms / websites\nsocial media\...          1         1.2
46  online job platforms / websites\nlinkedin or p...          1         1.2

================================================================================
biggest_difficulty
================================================================================

                                        category  frequency  percentage
0              lack of practical work experience         20        24.1
1       high competition for available positions         13        15.7
2                      location / transportation         13        15.7
3          limited job opportunities in my field         11        13.3
4                          salary levels offered         10        12.0
5                         discrimination or bias          6         7.2
6    lack of professional connections / networks          4         4.8
7                                          other          3         3.6
8  stress, discouragement, or loss of motivation          2         2.4
9            lack of technical or digital skills          1         1.2

================================================================================
difficult_job_search_stage
================================================================================

                                            category  frequency  percentage
0                 finding suitable job opportunities         27        32.5
1         i have not yet reached any of these stages         19        22.9
2                              receiving a job offer         10        12.0
3                      getting invited to interviews          9        10.8
4          deciding which opportunities to apply for          6         7.2
5  accepting an available offer because of salary...          5         6.0
6       performing well in interviews or assessments          4         4.8
7                        completing job applications          2         2.4
8                        staying in a job once hired          1         1.2

================================================================================
application_outcome
================================================================================

                                            category  frequency  percentage
0                      i rarely receive any response         36        43.4
1  i sometimes receive interviews but rarely prog...         12        14.5
2  i have received offers, but they were not suit...         11        13.3
3  i often reach later stages but do not receive ...          9        10.8
4          i receive rejections without an interview          8         9.6
5  i have received suitable offers but could not ...          7         8.4

================================================================================
experience_requirement
================================================================================

     category  frequency  percentage
0  very often         29        34.9
1   sometimes         25        30.1
2       often         16        19.3
3      rarely          6         7.2
4       never          6         7.2
5    not sure          1         1.2

================================================================================
entry_level_experience
================================================================================

     category  frequency  percentage
0       often         26        31.3
1   sometimes         24        28.9
2  very often         18        21.7
3      rarely          8         9.6
4       never          4         4.8
5    not sure          3         3.6

================================================================================
interview_without_offer
================================================================================

                           category  frequency  percentage
0                             never         26        31.3
1                         2–3 times         18        21.7
2                              once         17        20.5
3  i have never had a job interview         10        12.0
4                 more than 5 times          6         7.2
5                         4–5 times          6         7.2

================================================================================
employer_feedback
================================================================================

                              category  frequency  percentage
0  i usually do not receive a response         25        30.1
1                         almost never         23        27.7
2                               rarely         18        21.7
3                            sometimes         12        14.5
4                                often          5         6.0

In [14]:
entry_level_experience_order = [
    "never",
    "rarely",
    "sometimes",
    "often",
    "very often",
    "not sure"
]

df_youth["entry_level_experience"] = pd.Categorical(
    df_youth["entry_level_experience"],
    categories=entry_level_experience_order,
    ordered=True
)

print(df_youth["entry_level_experience"].cat.categories)

Index(['never', 'rarely', 'sometimes', 'often', 'very often', 'not sure'], dtype='object')

In [15]:
experience_requirement_order = [
    "never",
    "rarely",
    "sometimes",
    "often",
    "very often",
    "not sure"
]

df_youth["experience_requirement"] = pd.Categorical(
    df_youth["experience_requirement"],
    categories=experience_requirement_order,
    ordered=True
)

print(df_youth["experience_requirement"].cat.categories)

Index(['never', 'rarely', 'sometimes', 'often', 'very often', 'not sure'], dtype='object')

In [16]:
interview_without_offer_order = [
    "i have never had a job interview",
    "never",
    "once",
    "2–3 times",
    "4–5 times",
    "more than 5 times"
]

df_youth["interview_without_offer"] = pd.Categorical(
    df_youth["interview_without_offer"],
    categories=interview_without_offer_order,
    ordered=True
)

print(df_youth["interview_without_offer"].cat.categories)

Index(['i have never had a job interview', 'never', 'once', '2–3 times',
       '4–5 times', 'more than 5 times'],
      dtype='object')

In [17]:
job_search_duration_order = [
    "i am not currently looking",
    "less than 3 months",
    "3–6 months",
    "6–12 months",
    "more than 1 year",
    "more than 2 years"
]

df_youth["job_search_duration"] = pd.Categorical(
    df_youth["job_search_duration"],
    categories=job_search_duration_order,
    ordered=True
)

print(df_youth["job_search_duration"].cat.categories)

Index(['i am not currently looking', 'less than 3 months', '3–6 months',
       '6–12 months', 'more than 1 year', 'more than 2 years'],
      dtype='object')

In [18]:

# Replace NaN with "none" in applications_3m
df_youth["applications_3m"] = (
    df_youth["applications_3m"]
    .fillna("none")
    .str.lower()
    .str.strip()
)

# Check result
print(df_youth["applications_3m"].value_counts(dropna=False))

applications_3m
1–5             26
none            21
more than 20    17
6–10            12
11–20            7
Name: count, dtype: int64

In [19]:
#Education → job-search difficulties
#Education × Current status

pd.crosstab(
    df_youth["education_level"],
    df_youth["current_status"],
    normalize="index"
).mul(100).round(1)

current_status,i am currently unemployed and actively looking for work,i am currently unemployed but not actively looking for work,"i am working, but my current work does not provide the career opportunities, stability, or conditions i am looking for","i earn income through freelancing, temporary, informal, or occasional work, but i am looking for more stable employment",other
education_level,,,,,
bachelor’s degree,57.1,10.7,10.7,10.7,10.7
doctorate / phd,100.0,0.0,0.0,0.0,0.0
master’s degree,58.3,0.0,0.0,41.7,0.0
professional or online certificate(s),50.0,25.0,25.0,0.0,0.0
technical / vocational education,70.0,20.0,10.0,0.0,0.0

In [20]:
#Education × Job-search duration
pd.crosstab(
    df_youth["education_level"],
    df_youth["job_search_duration"],
    normalize="index"
).mul(100).round(1)

job_search_duration,i am not currently looking,less than 3 months,3–6 months,6–12 months,more than 1 year,more than 2 years
education_level,,,,,,
bachelor’s degree,21.4,25.0,16.1,19.6,16.1,1.8
doctorate / phd,0.0,0.0,0.0,0.0,0.0,100.0
master’s degree,8.3,25.0,16.7,33.3,0.0,16.7
professional or online certificate(s),0.0,25.0,50.0,0.0,0.0,25.0
technical / vocational education,10.0,10.0,0.0,10.0,40.0,30.0

In [21]:
job_search_duration_order = [
    "i am not currently looking",
    "less than 3 months",
    "3–6 months",
    "6–12 months",
    "more than 1 year",
    "more than 2 years"
]

df_youth["job_search_duration"] = pd.Categorical(
    df_youth["job_search_duration"],
    categories=job_search_duration_order,
    ordered=True
)

print(df_youth["job_search_duration"].cat.categories)

Index(['i am not currently looking', 'less than 3 months', '3–6 months',
       '6–12 months', 'more than 1 year', 'more than 2 years'],
      dtype='object')

In [22]:
#Education × Applications in the last 3 months
pd.crosstab(
    df_youth["education_level"],
    df_youth["applications_3m"],
    normalize="index"
).mul(100).round(1)

applications_3m                        11–20   1–5  6–10  more than 20  none
education_level
bachelor’s degree                        5.4  30.4  16.1          21.4  26.8
doctorate / phd                          0.0   0.0   0.0         100.0   0.0
master’s degree                          8.3  25.0  25.0          33.3   8.3
professional or online certificate(s)   25.0  50.0   0.0           0.0  25.0
technical / vocational education        20.0  40.0   0.0           0.0  40.0

In [23]:
print(df_youth["applications_3m"].unique())

['more than 20' '1–5' 'none' '11–20' '6–10']

In [24]:
application_order = [
    "none",
    "1–5",
    "6–10",
    "11–20",
    "more than 20"
]

df_youth["applications_3m"] = pd.Categorical(
    df_youth["applications_3m"],
    categories=application_order,
    ordered=True
)

In [25]:
#Current status × job-search situation
pd.crosstab(
    df_youth["current_status"],
    df_youth["job_search_duration"],
    normalize="index"
).mul(100).round(1)

job_search_duration,i am not currently looking,less than 3 months,3–6 months,6–12 months,more than 1 year,more than 2 years
current_status,,,,,,
i am currently unemployed and actively looking for work,4.1,30.6,14.3,24.5,12.2,14.3
i am currently unemployed but not actively looking for work,55.6,0.0,11.1,11.1,22.2,0.0
"i am working, but my current work does not provide the career opportunities, stability, or conditions i am looking for",12.5,0.0,0.0,12.5,62.5,12.5
"i earn income through freelancing, temporary, informal, or occasional work, but i am looking for more stable employment",18.2,27.3,36.4,18.2,0.0,0.0
other,66.7,16.7,16.7,0.0,0.0,0.0

In [26]:
pd.crosstab(
    df_youth["current_status"],
    df_youth["applications_3m"],
    normalize="index"
).mul(100).round(1)

applications_3m,none,1–5,6–10,11–20,more than 20
current_status,,,,,
i am currently unemployed and actively looking for work,12.2,24.5,20.4,12.2,30.6
i am currently unemployed but not actively looking for work,66.7,33.3,0.0,0.0,0.0
"i am working, but my current work does not provide the career opportunities, stability, or conditions i am looking for",37.5,50.0,12.5,0.0,0.0
"i earn income through freelancing, temporary, informal, or occasional work, but i am looking for more stable employment",9.1,54.5,9.1,9.1,18.2
other,83.3,16.7,0.0,0.0,0.0

In [27]:
#Job-search barriers
barrier_dummies = created_dummies["job_search_barriers"]

barrier_summary = pd.DataFrame({
    "frequency": df_youth[barrier_dummies].sum(),
    "percentage": df_youth[barrier_dummies].mean() * 100
})

barrier_summary["percentage"] = barrier_summary["percentage"].round(1)

barrier_summary = barrier_summary.sort_values(
    "frequency",
    ascending=False
)

display(barrier_summary)

                                                    frequency  percentage
job_search_barriers__lack_of_practical_work_exp...         36        43.4
job_search_barriers__location_of_available_jobs...         35        42.2
job_search_barriers__high_competition_for_avail...         32        38.6
job_search_barriers__limited_job_opportunities_...         28        33.7
job_search_barriers__transportation_or_commutin...         21        25.3
job_search_barriers__salary_levels_offered_by_e...         19        22.9
job_search_barriers__lack_of_professional_conne...         18        21.7
job_search_barriers__discrimination_or_bias_dur...         17        20.5
job_search_barriers__stress_discouragement_or_l...         10        12.0
job_search_barriers__lack_of_technical_or_digit...          9        10.8
job_search_barriers__lack_of_soft_skills_requir...          4         4.8

In [28]:
#Experience and skills
experience_vars = [
    "experience_requirement",
    "education_job_preparation",
    "entry_level_experience"
]

for col in experience_vars:
    print("\n" + "=" * 80)
    print(col)
    print("=" * 80)
    display(categorical_summary(df_youth, col))

================================================================================
experience_requirement
================================================================================

     category  frequency  percentage
0  very often         29        34.9
1   sometimes         25        30.1
2       often         16        19.3
3       never          6         7.2
4      rarely          6         7.2
5    not sure          1         1.2

================================================================================
education_job_preparation
================================================================================

                                            category  frequency  percentage
0                                         moderately         31        37.3
1                                           slightly         15        18.1
2                                               well         14        16.9
3                                          very well         12        14.5
4                                         not at all          6         7.2
5  i have not received relevant education or trai...          5         6.0

================================================================================
entry_level_experience
================================================================================

     category  frequency  percentage
0       often         26        31.3
1   sometimes         24        28.9
2  very often         18        21.7
3      rarely          8         9.6
4       never          4         4.8
5    not sure          3         3.6

In [29]:
df_youth["education_job_preparation"].value_counts(sort=False)

education_job_preparation
moderately                                            31
not at all                                             6
very well                                             12
slightly                                              15
well                                                  14
i have not received relevant education or training     5
Name: count, dtype: int64

In [30]:
education_job_preparation_order = [
    "not at all",
    "slightly",
    "moderately",
    "well",
    "very well",
    "i have not received relevant education or training"
]

df_youth["education_job_preparation"] = pd.Categorical(
    df_youth["education_job_preparation"],
    categories=education_job_preparation_order,
    ordered=True
)

print(df_youth["education_job_preparation"].cat.categories)

Index(['not at all', 'slightly', 'moderately', 'well', 'very well',
       'i have not received relevant education or training'],
      dtype='object')

In [31]:
skills_dummies = created_dummies["missing_skills"]

skills_summary = pd.DataFrame({
    "frequency": df_youth[skills_dummies].sum(),
    "percentage": df_youth[skills_dummies].mean() * 100
})

skills_summary["percentage"] = skills_summary["percentage"].round(1)

display(
    skills_summary.sort_values("frequency", ascending=False)
)

                                                    frequency  percentage
missing_skills__practical_work_experience                  32        38.6
missing_skills__technical_job_specific_skills              31        37.3
missing_skills__interview_skills                           21        25.3
missing_skills__english_or_other_language_skills           19        22.9
missing_skills__communication_skills                       16        19.3
missing_skills__knowledge_of_the_lebanese_job_m...         12        14.5
missing_skills__professional_certifications                 9        10.8
missing_skills__digital_skills                              8         9.6
missing_skills__problem_solving_critical_thinking           6         7.2
missing_skills__other                                       5         6.0

In [32]:
source_dummies = created_dummies["job_opportunity_source"]

source_summary = pd.DataFrame({
    "frequency": df_youth[source_dummies].sum(),
    "percentage": df_youth[source_dummies].mean() * 100
})

source_summary["percentage"] = source_summary["percentage"].round(1)

display(
    source_summary.sort_values("frequency", ascending=False)
)

                                                    frequency  percentage
job_opportunity_source__online_job_platforms_we...         54        65.1
job_opportunity_source__social_media                       39        47.0
job_opportunity_source__linkedin_or_professiona...         36        43.4
job_opportunity_source__friends_or_family                  35        42.2
job_opportunity_source__personal_or_professiona...         14        16.9
job_opportunity_source__ngo_or_community_organi...         14        16.9
job_opportunity_source__directly_from_employers             7         8.4
job_opportunity_source__university_educational_...          7         8.4
job_opportunity_source__recruitment_agency                  5         6.0
job_opportunity_source__other                               1         1.2

In [33]:
# ============================================================
# UNIQUE ANSWERS — FIELD OF STUDY
# ============================================================

unique_fields = (
    df_youth["field_of_study"]
    .dropna()
    .unique()
)

print(f"Number of unique answers: {len(unique_fields)}\n")

for i, field in enumerate(sorted(unique_fields), 1):
    print(f"{i}. {field}")

Number of unique answers: 60

1. accounting
2. advertising and marketing communications
3. architecture
4. biology
5. biomedical sciences
6. biomedical scientist
7. bmis
8. business
9. business information technology
10. business marketing
11. business/ finance and financial institutions
12. cce
13. chemistry
14. communication and computer engineering
15. communication engineering
16. computer and communication engineering
17. computer engineering
18. computer science
19. data science
20. dental laboratory- lawyer
21. dentistry
22. designer
23. ecology - wildlife conservation
24. electrical engineering
25. electro mechanics / renewable energy
26. engineering and law
27. english
28. english literature
29. estetich
30. graphic design
31. hospitality and tourism management
32. human resources management
33. information technology
34. interior design
35. law
36. litterature francaise
37. manage information system
38. management information system
39. management information systems
40. medical social worker
41. medicine
42. mis
43. nursing and english literature
44. nutrition and dietetics
45. psychology
46. psychology/graphic design
47. social sciences
48. social worker
49. statistics
50. teaching english as a second language
51. technology
52. translation and interpretation
53. translation studies
54. الرقابة الصحية وسلامة الغذاء
55. الصف التاسع معلم حلاقه
56. علم الاجتماع وإدارة الموارد البشرية
57. علوم اجتماعية
58. علوم اجتماعية-social science
59. علوم سياسية وادارية
60. هندسة كمبيوتر

In [34]:
# ============================================================
# GROUP FIELD OF STUDY INTO 6 DEPARTMENTS + OTHER
# ============================================================

field_department_map = {

    # --------------------------------------------------------
    # 1. BUSINESS & MANAGEMENT
    # --------------------------------------------------------
    "accounting": "Business & Management",
    "advertising and marketing communications": "Business & Management",
    "bmis": "Business & Management",
    "business": "Business & Management",
    "business information technology": "Business & Management",
    "business marketing": "Business & Management",
    "business/ finance and financial institutions": "Business & Management",
    "human resources management": "Business & Management",
    "manage information system": "Business & Management",
    "management information system": "Business & Management",
    "management information systems": "Business & Management",
    "mis": "Business & Management",
    "علم الاجتماع وإدارة الموارد البشرية": "Business & Management",

    # --------------------------------------------------------
    # 2. COMPUTING, DATA & IT
    # --------------------------------------------------------
    "computer science": "Computing, Data & IT",
    "data science": "Computing, Data & IT",
    "information technology": "Computing, Data & IT",
    "statistics": "Computing, Data & IT",
    "technology": "Computing, Data & IT",

    # --------------------------------------------------------
    # 3. ENGINEERING
    # --------------------------------------------------------
    "cce": "Engineering",
    "communication and computer engineering": "Engineering",
    "communication engineering": "Engineering",
    "computer and communication engineering": "Engineering",
    "computer engineering": "Engineering",
    "electrical engineering": "Engineering",
    "electro mechanics / renewable energy": "Engineering",
    "هندسة كمبيوتر": "Engineering",

    # --------------------------------------------------------
    # 4. HEALTH & MEDICAL SCIENCES
    # --------------------------------------------------------
    "biology": "Health & Medical Sciences",
    "biomedical sciences": "Health & Medical Sciences",
    "biomedical scientist": "Health & Medical Sciences",
    "dentistry": "Health & Medical Sciences",
    "medical social worker": "Health & Medical Sciences",
    "medicine": "Health & Medical Sciences",
    "nursing and english literature": "Health & Medical Sciences",
    "nutrition and dietetics": "Health & Medical Sciences",
    "الرقابة الصحية وسلامة الغذاء": "Health & Medical Sciences",

    # --------------------------------------------------------
    # 5. SOCIAL SCIENCES & PSYCHOLOGY
    # --------------------------------------------------------
    "psychology": "Social Sciences & Psychology",
    "social sciences": "Social Sciences & Psychology",
    "social worker": "Social Sciences & Psychology",
    "علوم اجتماعية": "Social Sciences & Psychology",
    "علوم اجتماعية-social science": "Social Sciences & Psychology",
    "علوم سياسية وادارية": "Social Sciences & Psychology",

    # --------------------------------------------------------
    # 6. ARTS, DESIGN & ARCHITECTURE
    # --------------------------------------------------------
    "architecture": "Arts, Design & Architecture",
    "designer": "Arts, Design & Architecture",
    "graphic design": "Arts, Design & Architecture",
    "interior design": "Arts, Design & Architecture",

    # --------------------------------------------------------
    # OTHER
    # --------------------------------------------------------
    "accounting": "Business & Management",
    "dental laboratory- lawyer": "Other",
    "ecology - wildlife conservation": "Other",
    "engineering and law": "Other",
    "english": "Other",
    "english literature": "Other",
    "estetich": "Other",
    "hospitality and tourism management": "Other",
    "law": "Other",
    "litterature francaise": "Other",
    "psychology/graphic design": "Other",
    "teaching english as a second language": "Other",
    "translation and interpretation": "Other",
    "translation studies": "Other",
    "الصف التاسع معلم حلاقه": "Other",
    "chemistry": "Other",
}

In [35]:
# ============================================================
# CREATE NEW GROUPED VARIABLE
# ============================================================

df_youth["field_department"] = (
    df_youth["field_of_study"]
    .map(field_department_map)
)

print(df_youth["field_department"].value_counts(dropna=False))

field_department
Business & Management           17
Other                           16
Computing, Data & IT            13
Engineering                     11
Health & Medical Sciences       10
Arts, Design & Architecture      8
Social Sciences & Psychology     7
NaN                              1
Name: count, dtype: int64

C:\Users\User\AppData\Local\Temp\ipykernel_24808\821612479.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_youth["field_department"] = (

In [36]:
df_youth["field_department"] = df_youth["field_department"].fillna("Other")

In [37]:
# ============================================================
# CHECK UNMAPPED FIELDS
# ============================================================

unmapped = df_youth.loc[
    df_youth["field_department"].isna(),
    "field_of_study"
].dropna().unique()

print("Unmapped fields:")
for field in sorted(unmapped):
    print("-", field)

Unmapped fields:

In [38]:
pd.crosstab(
    df_youth["field_department"],
    df_youth["education_job_preparation"],
    normalize="index"
).mul(100).round(1)

education_job_preparation,not at all,slightly,moderately,well,very well,i have not received relevant education or training
field_department,,,,,,
"Arts, Design & Architecture",12.5,12.5,25.0,12.5,37.5,0.0
Business & Management,5.9,17.6,29.4,35.3,5.9,5.9
"Computing, Data & IT",0.0,30.8,61.5,0.0,7.7,0.0
Engineering,0.0,36.4,45.5,0.0,9.1,9.1
Health & Medical Sciences,10.0,0.0,50.0,20.0,20.0,0.0
Other,11.8,11.8,23.5,29.4,17.6,5.9
Social Sciences & Psychology,14.3,14.3,28.6,0.0,14.3,28.6

In [39]:
pd.crosstab(
    df_youth["experience_requirement"],
    df_youth["entry_level_experience"],
    normalize="index"
).mul(100).round(1)

entry_level_experience  never  rarely  sometimes  often  very often  not sure
experience_requirement
never                    33.3    33.3       16.7    0.0         0.0      16.7
rarely                   16.7    33.3       16.7   16.7         0.0      16.7
sometimes                 0.0     4.0       48.0   28.0        20.0       0.0
often                     0.0     6.2       25.0   62.5         6.2       0.0
very often                3.4     3.4       20.7   27.6        41.4       3.4
not sure                  0.0   100.0        0.0    0.0         0.0       0.0

In [40]:
pd.crosstab(
    df_youth["job_search_duration"],
    df_youth["missing_skills__practical_work_experience"],
    normalize="index"
).mul(100).round(1)

missing_skills__practical_work_experience     0     1
job_search_duration
i am not currently looking                 71.4  28.6
less than 3 months                         47.4  52.6
3–6 months                                 61.5  38.5
6–12 months                                68.8  31.2
more than 1 year                           61.5  38.5
more than 2 years                          62.5  37.5

In [41]:
pd.crosstab(
    df_youth["job_search_duration"],
    df_youth["job_search_barriers__lack_of_practical_work_experience"],
    normalize="index"
).mul(100).round(1)

job_search_barriers__lack_of_practical_work_experience     0     1
job_search_duration
i am not currently looking                              64.3  35.7
less than 3 months                                      52.6  47.4
3–6 months                                              46.2  53.8
6–12 months                                             81.2  18.8
more than 1 year                                        53.8  46.2
more than 2 years                                       25.0  75.0

In [42]:
pd.crosstab(
    df_youth["applications_3m"],
    df_youth["application_outcome"],
    normalize="index"
).mul(100).round(1)

application_outcome,"i have received offers, but they were not suitable",i have received suitable offers but could not accept them,i often reach later stages but do not receive offers,i rarely receive any response,i receive rejections without an interview,i sometimes receive interviews but rarely progress further
applications_3m,,,,,,
none,19.0,28.6,14.3,23.8,4.8,9.5
1–5,23.1,3.8,11.5,46.2,3.8,11.5
6–10,0.0,0.0,8.3,58.3,16.7,16.7
11–20,14.3,0.0,0.0,57.1,14.3,14.3
more than 20,0.0,0.0,11.8,47.1,17.6,23.5

In [43]:
pd.crosstab(
    df_youth["interview_without_offer"],
    df_youth["interview_difficulties__communicating_confidently"],
    normalize="index"
).mul(100).round(1)

interview_difficulties__communicating_confidently     0     1
interview_without_offer
i have never had a job interview                   90.0  10.0
never                                              88.5  11.5
once                                               76.5  23.5
2–3 times                                          66.7  33.3
4–5 times                                          66.7  33.3
more than 5 times                                  83.3  16.7

In [44]:
# ============================================================
# RANK JOB-SEARCH BARRIERS
# ============================================================

barrier_cols = {
    "Lack of practical work experience":
        "job_search_barriers__lack_of_practical_work_experience",

    "Lack of technical/digital skills":
        "job_search_barriers__lack_of_technical_or_digital_skills_required_by_employers",

    "Lack of soft skills":
        "job_search_barriers__lack_of_soft_skills_required_by_employers_e_g_communication_teamwork_adaptability",

    "Lack of professional connections/networking":
        "job_search_barriers__lack_of_professional_connections_or_networking_opportunities",

    "Limited job opportunities in my field":
        "job_search_barriers__limited_job_opportunities_in_my_field",

    "High competition":
        "job_search_barriers__high_competition_for_available_positions",

    "Location/distance":
        "job_search_barriers__location_of_available_jobs_distance_from_where_i_live",

    "Transportation difficulties":
        "job_search_barriers__transportation_or_commuting_difficulties",

    "Salary levels offered":
        "job_search_barriers__salary_levels_offered_by_employers",

    "Discrimination/bias":
        "job_search_barriers__discrimination_or_bias_during_the_hiring_process",

    "Stress/discouragement":
        "job_search_barriers__stress_discouragement_or_loss_of_motivation_during_the_job_search"
}

barrier_summary = []

for label, col in barrier_cols.items():
    count = df_youth[col].sum()
    percentage = count / len(df_youth) * 100

    barrier_summary.append({
        "barrier": label,
        "frequency": int(count),
        "percentage": round(percentage, 1)
    })

barrier_summary = (
    pd.DataFrame(barrier_summary)
    .sort_values("percentage", ascending=False)
    .reset_index(drop=True)
)

barrier_summary.index = barrier_summary.index + 1

display(barrier_summary)

                                        barrier  frequency  percentage
1             Lack of practical work experience         36        43.4
2                             Location/distance         35        42.2
3                              High competition         32        38.6
4         Limited job opportunities in my field         28        33.7
5                   Transportation difficulties         21        25.3
6                         Salary levels offered         19        22.9
7   Lack of professional connections/networking         18        21.7
8                           Discrimination/bias         17        20.5
9                         Stress/discouragement         10        12.0
10             Lack of technical/digital skills          9        10.8
11                          Lack of soft skills          4         4.8

In [45]:
biggest_difficulty_summary = (
    df_youth["biggest_difficulty"]
    .value_counts(dropna=False)
    .rename_axis("biggest_difficulty")
    .reset_index(name="frequency")
)

biggest_difficulty_summary["percentage"] = (
    biggest_difficulty_summary["frequency"]
    / len(df_youth) * 100
).round(1)

display(biggest_difficulty_summary)

                              biggest_difficulty  frequency  percentage
0              lack of practical work experience         20        24.1
1       high competition for available positions         13        15.7
2                      location / transportation         13        15.7
3          limited job opportunities in my field         11        13.3
4                          salary levels offered         10        12.0
5                         discrimination or bias          6         7.2
6    lack of professional connections / networks          4         4.8
7                                          other          3         3.6
8  stress, discouragement, or loss of motivation          2         2.4
9            lack of technical or digital skills          1         1.2

In [46]:
source_cols = [
    col for col in df_youth.columns
    if col.startswith("job_opportunity_source__")
]

source_summary = []

for col in source_cols:
    count = df_youth[col].sum()

    source_summary.append({
        "opportunity_source": col.replace(
            "job_opportunity_source__", ""
        ),
        "frequency": int(count),
        "percentage": round(count / len(df_youth) * 100, 1)
    })

source_summary = (
    pd.DataFrame(source_summary)
    .sort_values("percentage", ascending=False)
    .reset_index(drop=True)
)

source_summary.index += 1

display(source_summary)

                      opportunity_source  frequency  percentage
1          online_job_platforms_websites         54        65.1
2                           social_media         39        47.0
3     linkedin_or_professional_platforms         36        43.4
4                      friends_or_family         35        42.2
5   personal_or_professional_connections         14        16.9
6          ngo_or_community_organization         14        16.9
7                directly_from_employers          7         8.4
8     university_educational_institution          7         8.4
9                     recruitment_agency          5         6.0
10                                 other          1         1.2

In [47]:
support_cols = [
    col for col in df_youth.columns
    if col.startswith("employment_support__")
]

support_summary = []

for col in support_cols:
    count = df_youth[col].sum()

    support_summary.append({
        "support": col.replace(
            "employment_support__", ""
        ),
        "frequency": int(count),
        "percentage": round(count / len(df_youth) * 100, 1)
    })

support_summary = (
    pd.DataFrame(support_summary)
    .sort_values("percentage", ascending=False)
    .reset_index(drop=True)
)

support_summary.index += 1

display(support_summary)

                                      support  frequency  percentage
1   paid_internship_practical_work_experience         54        65.1
2      technical_job_specific_skills_training         23        27.7
3     networking_opportunities_with_employers         17        20.5
4                      cv_application_support         14        16.9
5                       interview_preparation         14        16.9
6                   english_language_training         14        16.9
7                      transportation_support         13        15.7
8                     digital_skills_training         13        15.7
9               mentorship_from_professionals          9        10.8
10                            career_guidance          8         9.6
11         apprenticeships_workplace_training          7         8.4
12     financial_support_during_job_searching          6         7.2
13                professional_certifications          6         7.2
14                       soft_skills_training          6         7.2
15                      job_matching_services          4         4.8
16                   entrepreneurship_support          3         3.6

In [48]:
pd.crosstab(
    df_youth["field_department"],
    df_youth["job_search_barriers__lack_of_practical_work_experience"]
)

job_search_barriers__lack_of_practical_work_experience   0  1
field_department
Arts, Design & Architecture                              6  2
Business & Management                                    9  8
Computing, Data & IT                                     9  4
Engineering                                              3  8
Health & Medical Sciences                                7  3
Other                                                   10  7
Social Sciences & Psychology                             3  4

In [49]:
from scipy.stats import chi2_contingency
import numpy as np

table = pd.crosstab(
    df_youth["field_department"],
    df_youth["job_search_barriers__lack_of_practical_work_experience"]
)

chi2, p, dof, expected = chi2_contingency(table)

n = table.sum().sum()
r, k = table.shape

cramers_v = np.sqrt(
    chi2 / (n * min(r - 1, k - 1))
)

print("Chi-square:", round(chi2, 3))
print("Degrees of freedom:", dof)
print("p-value:", round(p, 4))
print("Cramér's V:", round(cramers_v, 3))

print("\nMinimum expected frequency:", round(expected.min(), 2))

Chi-square: 7.195
Degrees of freedom: 6
p-value: 0.3032
Cramér's V: 0.294

Minimum expected frequency: 3.04

In [50]:
#no significant association between field of study and lack of practical work experience as a barrier (p > 0.05).

In [51]:
df_youth["education_job_preparation"].value_counts(dropna=False)

education_job_preparation
moderately                                            31
slightly                                              15
well                                                  14
very well                                             12
not at all                                             6
i have not received relevant education or training     5
Name: count, dtype: int64

In [52]:
from scipy.stats import mannwhitneyu

prep_mapping = {
    "not at all": 1,
    "slightly": 2,
    "moderately": 3,
    "well": 4,
    "very well": 5
}

# Temporary numeric version
prep_numeric = df_youth["education_job_preparation"].map(prep_mapping)

# Split by lack of practical work experience
group_0 = prep_numeric[
    df_youth["job_search_barriers__lack_of_practical_work_experience"] == 0
].dropna()

group_1 = prep_numeric[
    df_youth["job_search_barriers__lack_of_practical_work_experience"] == 1
].dropna()

# Mann–Whitney U test
u_stat, p_value = mannwhitneyu(
    group_0,
    group_1,
    alternative="two-sided"
)

print("Did NOT select lack of practical experience:", len(group_0))
print("Selected lack of practical experience:", len(group_1))
print("Mann–Whitney U:", u_stat)
print("p-value:", p_value)

Did NOT select lack of practical experience: 45
Selected lack of practical experience: 33
Mann–Whitney U: 951.0
p-value: 0.02832405896256338

In [53]:
print("Median - Did NOT select:", group_0.median())
print("Median - Selected:", group_1.median())

print("\nDistribution:")
print(pd.DataFrame({
    "Did NOT select": group_0.value_counts().sort_index(),
    "Selected": group_1.value_counts().sort_index()
}).fillna(0))

Median - Did NOT select: 3.0
Median - Selected: 3.0

Distribution:
                           Did NOT select  Selected
education_job_preparation
1.0                                     4         2
2.0                                     6         9
3.0                                    15        16
4.0                                     9         5
5.0                                    11         1

In [54]:
#Young people who feel less prepared by their education or training are more likely to say that
# lack of practical work experience is a problem when looking for a job.

In [55]:
#segmentation analysis can't be applied because the sample size is too small for some of the categories, leading to unreliable results.

In [57]:
#save the cleaned and analyzed dataset to a new Excel file
output_path = r"C:\Users\User\Desktop\youth unemployement\youth_data_cleaned_analyzed.xlsx"
df_youth.to_excel(output_path, index=False)